import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'bn';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navbar
    'nav.home': 'Home',
    'nav.features': 'Features',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.signIn': 'Sign In',
    'nav.getStarted': 'Get Started',
    'nav.dashboard': 'Dashboard',
    'nav.logout': 'Logout Session',
    'nav.settings': 'Settings',
    'nav.profile': 'Profile',
    'nav.founderPanel': 'Founder Panel',
    'nav.masters': 'Masters',
    'nav.createLedger': 'Create Ledger',
    'nav.createItem': 'Create Item',
    'nav.godowns': 'Godowns',
    'nav.employeeMaster': 'Employee Master',
    'nav.chartOfAccounts': 'Chart of Accounts',
    'nav.itemMaster': 'Item Master',
    'nav.transactions': 'Transactions',
    'nav.voucherEntry': 'Voucher Entry',
    'nav.payroll': 'Payroll',
    'nav.payrollManagement': 'Payroll Management',
    'nav.production': 'Production',
    'nav.orderManagement': 'Order Management',
    'nav.machineManagement': 'Machine Management',
    'nav.productionReports': 'Production Reports',
    'nav.reports': 'Reports',
    'nav.daybook': 'Daybook',
    'nav.balanceSheet': 'Balance Sheet',
    'nav.trialBalance': 'Trial Balance',
    'nav.profitAndLoss': 'Profit & Loss',
    'nav.ratioAnalysis': 'Ratio Analysis',
    'nav.financialInsights': 'Financial Insights',
    'nav.stockSummary': 'Stock Summary',
    'nav.ledgerStatement': 'Ledger Statement',
    'nav.salesPerformance': 'Sales Performance',
    'nav.companyInfo': 'Company Info',
    'nav.uiCustomization': 'UI Customization',
    'nav.voucherSettings': 'Voucher Settings',
    'nav.printSettings': 'Print Settings',
    'nav.f11Features': 'F11 Features',
    'nav.security': 'Security',
    'nav.notifications': 'Notifications',
    'nav.whatsappTemplates': 'WhatsApp Templates',
    'nav.utilities': 'Utilities',
    'nav.companyManagement': 'Company Management',
    'nav.notesMemo': 'Notes / Memo',
    'nav.userManagement': 'User Management',
    'nav.menu': 'Menu',
    'nav.theme': 'Select Theme',

    // Home
    'home.heroTitle': 'Manage Your Business With Intelligence',
    'home.heroSubtitle': 'The all-in-one ERP solution for modern enterprises. Streamline operations, gain real-time insights, and scale your business with confidence.',
    'home.startTrial': 'Start Free Trial',
    'home.viewFeatures': 'View Features',
    'home.statsClients': 'Active Clients',
    'home.statsUptime': 'Uptime Rate',
    'home.statsSupport': 'Expert Support',
    'home.statsExperience': 'Years Experience',
    'home.featuresTitle': 'Everything You Need',
    'home.featuresSubtitle': 'Powerful tools to help you manage every aspect of your business from a single, unified platform.',
    'home.feature1Title': 'Financial Insights',
    'home.feature1Desc': 'Real-time reporting and analytics to help you make data-driven decisions.',
    'home.feature2Title': 'Inventory Control',
    'home.feature2Desc': 'Track stock levels, manage warehouses, and optimize your supply chain.',
    'home.feature3Title': 'Team Collaboration',
    'home.feature3Desc': 'Manage employees, payroll, and permissions with ease.',
    'home.feature4Title': 'Enterprise Security',
    'home.feature4Desc': 'Bank-grade security to keep your sensitive business data safe.',
    'home.feature5Title': 'Fast Performance',
    'home.feature5Desc': 'Optimized for speed to ensure your business never slows down.',
    'home.feature6Title': 'Cloud Access',
    'home.feature6Desc': 'Access your business data from anywhere in the world, on any device.',
    'home.ctaTitle': 'Ready to Transform Your Business?',
    'home.ctaSubtitle': 'Join hundreds of successful companies already using our ERP system to power their growth.',
    'home.getStarted': 'Get Started Now',

    // Footer
    'footer.description': 'A comprehensive ERP solution designed to streamline your business operations, from inventory management to financial reporting.',
    'footer.product': 'Product',
    'footer.legal': 'Legal',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',

    // Auth
    'auth.signInTitle': 'Sign in to ERP System',
    'auth.signInSubtitle': 'Enter your details below to access your account.',
    'auth.email': 'Email Address',
    'auth.password': 'Password',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.signInButton': 'Sign In',
    'auth.noAccount': "Don't have an account?",
    'auth.createAccount': 'Create one',
    'auth.registerTitle': 'Create your Account',
    'auth.registerSubtitle': 'Join us today and start managing your business smarter.',
    'auth.fullName': 'Full Name',
    'auth.confirmPassword': 'Confirm Password',
    'auth.registerButton': 'Create Account',
    'auth.haveAccount': 'Already have an account?',

    // Dashboard
    'dash.welcome': 'Welcome back',
    'dash.overview': 'Dashboard Overview',
    'dash.financialSummary': 'Financial Summary',
    'dash.kpi': 'Key Performance Indicators',
    'dash.revenue': 'Total Revenue',
    'dash.profit': 'Net Profit',
    'dash.activeLedgers': 'Active Ledgers',
    'dash.stockValue': 'Stock Value',
    'dash.activeUsers': 'Active Users',
    'dash.newOrders': 'New Orders',
    'dash.pendingTasks': 'Pending Tasks',
    'dash.recentActivity': 'Recent Activity',
    'dash.recentTransactions': 'Recent Transactions',
    'dash.viewAll': 'View All',
    'dash.viewDaybook': 'View Daybook',
    'dash.quickActions': 'Quick Actions',
    'dash.voucher': 'Voucher',
    'dash.item': 'Item',
    'dash.ledger': 'Ledger',
    'dash.godown': 'Godown',
    'dash.users': 'Users',
    'dash.revenueTrajectory': 'Revenue Trajectory',
    'dash.expenseDistribution': 'Expense Distribution',
    'dash.netProfitMargin': 'Net Profit Margin',
    'dash.cashFlowProjection': 'Cash Flow Projection',
    'dash.gateway': 'Gateway',
    'dash.gatewayOf': 'Gateway of',
    'dash.technicalOverview': 'Technical Overview',
    'dash.financialYear': 'Financial Year',
    'dash.from': 'From',
    'dash.to': 'To',
    'dash.trialPeriod': 'Trial Period',
    'dash.subscriptionActive': 'Subscription Active',
    'dash.subscriptionInactive': 'Subscription Inactive',
    'dash.plan': 'Plan',
    'dash.daysRemaining': 'days remaining',
    'dash.expiresOn': 'Expires On',
    'dash.notSet': 'Not Set',
    'dash.renewPlan': 'Renew Plan',
    'dash.monthlySalesTrend': 'Monthly Sales Trend',
    'dash.performanceMetrics': 'Performance Metrics',
    'dash.revenueTarget': 'Revenue Target',
    'dash.profitMargin': 'Profit Margin',
    'dash.stockTurnover': 'Stock Turnover',
    'dash.collectionEfficiency': 'Collection Efficiency',
    'dash.support': 'Support',
    'dash.documentation': 'Documentation',
    'dash.systemStatus': 'System Status',
    'dash.online': 'Online',
    'dash.noRecentTransactions': 'No recent transactions',

    // Settings
    'settings.title': 'Settings',
    'settings.systemSettings': 'System Settings',
    'settings.configureEnvironment': 'Configure your ERP environment',
    'settings.profile': 'Profile Settings',
    'settings.language': 'Language',
    'settings.selectLanguage': 'Select Language',
    'settings.notifications': 'Notifications',
    'settings.security': 'Security',
    'settings.save': 'Save Changes',
    'settings.companyInfo': 'Company Information',
    'settings.uiCustomization': 'UI Customization',
    'settings.reportSettings': 'Report Settings',
    'settings.voucherSettings': 'Voucher Settings',
    'settings.printSettings': 'Print Settings',
    'settings.f11Features': 'F11 Features',
    'settings.whatsappTemplates': 'WhatsApp Templates',
    'settings.shortcuts': 'Shortcuts',
    'settings.backupExport': 'Backup & Export',
    'settings.integrations': 'Integrations',
    'settings.voucherConfiguration': 'Voucher Configuration',
    'settings.referenceNoFormat': 'Reference No. Default Format',
    'settings.fieldVisibility': 'Field Visibility',
    'settings.showFreeQty': 'Show Free Quantity',
    'settings.showFreeQtyDesc': 'Enable/Disable Free Quantity column in vouchers.',
    'settings.showDiscPercent': 'Show Discount %',
    'settings.showDiscPercentDesc': 'Enable/Disable Discount percentage column.',
    'settings.showTaxPercent': 'Show Tax %',
    'settings.showTaxPercentDesc': 'Enable/Disable Tax percentage column.',
    'settings.theme': 'Select Theme',
    'settings.uiStyle': 'UI Style',
    'settings.layoutWidth': 'Layout Width',
    'settings.sidebarExpanded': 'Sidebar Expanded by Default',
    'settings.menuBarStyle': 'Menu Bar Style',
    'settings.glassBackground': 'Glass Background Effect',
    'settings.notificationAnimation': 'Notification Animation',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'An error occurred',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.save': 'Save',
    'common.refresh': 'Refresh',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.actions': 'Actions',
    'common.date': 'Date',
    'common.amount': 'Amount',
    'common.status': 'Status',
    'common.type': 'Type',
    'common.particulars': 'Particulars',
    'common.voucherNo': 'Voucher No.'
  },
  bn: {
    // Navbar
    'nav.home': 'হোম',
    'nav.features': 'বৈশিষ্ট্য',
    'nav.about': 'আমাদের সম্পর্কে',
    'nav.contact': 'যোগাযোগ',
    'nav.signIn': 'লগইন',
    'nav.getStarted': 'শুরু করুন',
    'nav.dashboard': 'ড্যাশবোর্ড',
    'nav.logout': 'লগআউট সেশন',
    'nav.settings': 'সেটিংস',
    'nav.profile': 'প্রোফাইল',
    'nav.founderPanel': 'ফাউন্ডার প্যানেল',
    'nav.masters': 'মাস্টার্স',
    'nav.createLedger': 'লেজার তৈরি করুন',
    'nav.createItem': 'আইটেম তৈরি করুন',
    'nav.godowns': 'গোডাউন',
    'nav.employeeMaster': 'কর্মচারী মাস্টার',
    'nav.chartOfAccounts': 'চার্ট অফ অ্যাকাউন্টস',
    'nav.itemMaster': 'আইটেম মাস্টার',
    'nav.transactions': 'লেনদেন',
    'nav.voucherEntry': 'ভাউচার এন্ট্রি',
    'nav.payroll': 'পেরোল',
    'nav.payrollManagement': 'পেরোল ম্যানেজমেন্ট',
    'nav.production': 'উৎপাদন',
    'nav.orderManagement': 'অর্ডার ম্যানেজমেন্ট',
    'nav.machineManagement': 'মেশিন ম্যানেজমেন্ট',
    'nav.productionReports': 'উৎপাদন রিপোর্ট',
    'nav.reports': 'রিপোর্ট',
    'nav.daybook': 'ডে-বুক',
    'nav.balanceSheet': 'ব্যালেন্স শিট',
    'nav.trialBalance': 'ট্রায়াল ব্যালেন্স',
    'nav.profitAndLoss': 'লাভ ও ক্ষতি',
    'nav.ratioAnalysis': 'অনুপাত বিশ্লেষণ',
    'nav.financialInsights': 'আর্থিক অন্তর্দৃষ্টি',
    'nav.stockSummary': 'স্টক সারাংশ',
    'nav.ledgerStatement': 'লেজার স্টেটমেন্ট',
    'nav.salesPerformance': 'বিক্রয় কর্মক্ষমতা',
    'nav.companyInfo': 'কোম্পানির তথ্য',
    'nav.uiCustomization': 'UI কাস্টমাইজেশন',
    'nav.voucherSettings': 'ভাউচার সেটিংস',
    'nav.printSettings': 'প্রিন্ট সেটিংস',
    'nav.f11Features': 'F11 ফিচারসমূহ',
    'nav.security': 'নিরাপত্তা',
    'nav.notifications': 'নোটিফিকেশন',
    'nav.whatsappTemplates': 'হোয়াটসঅ্যাপ টেমপ্লেট',
    'nav.utilities': 'ইউটিলিটিস',
    'nav.companyManagement': 'কোম্পানি ম্যানেজমেন্ট',
    'nav.notesMemo': 'নোট / মেমো',
    'nav.userManagement': 'ব্যবহারকারী ম্যানেজমেন্ট',
    'nav.menu': 'মেনু',
    'nav.theme': 'থিম নির্বাচন করুন',

    // Home
    'home.heroTitle': 'বুদ্ধিমত্তার সাথে আপনার ব্যবসা পরিচালনা করুন',
    'home.heroSubtitle': 'আধুনিক এন্টারপ্রাইজের জন্য অল-ইন-ওয়ান ইআরপি সমাধান। অপারেশন সহজ করুন, রিয়েল-টাইম ইনসাইট পান এবং আত্মবিশ্বাসের সাথে আপনার ব্যবসা বৃদ্ধি করুন।',
    'home.startTrial': 'ফ্রি ট্রায়াল শুরু করুন',
    'home.viewFeatures': 'বৈশিষ্ট্য দেখুন',
    'home.statsClients': 'সক্রিয় ক্লায়েন্ট',
    'home.statsUptime': 'আপটাইম রেট',
    'home.statsSupport': 'বিশেষজ্ঞ সাপোর্ট',
    'home.statsExperience': 'বছরের অভিজ্ঞতা',
    'home.featuresTitle': 'আপনার যা কিছু প্রয়োজন',
    'home.featuresSubtitle': 'একটি একক প্ল্যাটফর্ম থেকে আপনার ব্যবসার প্রতিটি দিক পরিচালনা করতে সাহায্য করার জন্য শক্তিশালী টুলস।',
    'home.feature1Title': 'আর্থিক অন্তর্দৃষ্টি',
    'home.feature1Desc': 'আপনাকে ডেটা-চালিত সিদ্ধান্ত নিতে সাহায্য করার জন্য রিয়েল-টাইম রিপোর্টিং এবং বিশ্লেষণ।',
    'home.feature2Title': 'ইনভেন্টরি নিয়ন্ত্রণ',
    'home.feature2Desc': 'স্টক লেভেল ট্র্যাক করুন, গুদাম পরিচালনা করুন এবং আপনার সাপ্লাই চেইন অপ্টিমাইজ করুন।',
    'home.feature3Title': 'টিম সহযোগিতা',
    'home.feature3Desc': 'সহজেই কর্মচারী, বেতন এবং অনুমতি পরিচালনা করুন।',
    'home.feature4Title': 'এন্টারপ্রাইজ নিরাপত্তা',
    'home.feature4Desc': 'আপনার সংবেদনশীল ব্যবসায়িক ডেটা নিরাপদ রাখতে ব্যাংক-গ্রেড নিরাপত্তা।',
    'home.feature5Title': 'দ্রুত পারফরম্যান্স',
    'home.feature5Desc': 'আপনার ব্যবসা যাতে কখনও ধীর না হয় তা নিশ্চিত করতে গতির জন্য অপ্টিমাইজ করা হয়েছে।',
    'home.feature6Title': 'ক্লাউড অ্যাক্সেস',
    'home.feature6Desc': 'যেকোনো ডিভাইস থেকে বিশ্বের যেকোনো প্রান্ত থেকে আপনার ব্যবসায়িক ডেটা অ্যাক্সেস করুন।',
    'home.ctaTitle': 'আপনার ব্যবসা পরিবর্তন করতে প্রস্তুত?',
    'home.ctaSubtitle': 'শত শত সফল কোম্পানির সাথে যোগ দিন যারা ইতিমধ্যে তাদের ব্যবসার প্রবৃদ্ধির জন্য আমাদের ইআরপি সিস্টেম ব্যবহার করছে।',
    'home.getStarted': 'এখনই শুরু করুন',

    // Footer
    'footer.description': 'একটি ব্যাপক ইআরপি সমাধান যা আপনার ব্যবসার কার্যক্রমকে সহজতর করার জন্য ডিজাইন করা হয়েছে, ইনভেন্টরি ম্যানেজমেন্ট থেকে শুরু করে আর্থিক রিপোর্টিং পর্যন্ত।',
    'footer.product': 'পণ্য',
    'footer.legal': 'আইনি',
    'footer.privacy': 'গোপনীয়তা নীতি',
    'footer.terms': 'পরিষেবার শর্তাবলী',

    // Auth
    'auth.signInTitle': 'ইআরপি সিস্টেমে সাইন ইন করুন',
    'auth.signInSubtitle': 'আপনার অ্যাকাউন্টে প্রবেশ করতে নিচে আপনার বিবরণ দিন।',
    'auth.email': 'ইমেইল ঠিকানা',
    'auth.password': 'পাসওয়ার্ড',
    'auth.forgotPassword': 'পাসওয়ার্ড ভুলে গেছেন?',
    'auth.signInButton': 'সাইন ইন',
    'auth.noAccount': "অ্যাকাউন্ট নেই?",
    'auth.createAccount': 'একটি তৈরি করুন',
    'auth.registerTitle': 'আপনার অ্যাকাউন্ট তৈরি করুন',
    'auth.registerSubtitle': 'আজই আমাদের সাথে যোগ দিন এবং স্মার্টলি আপনার ব্যবসা পরিচালনা শুরু করুন।',
    'auth.fullName': 'পুরো নাম',
    'auth.confirmPassword': 'পাসওয়ার্ড নিশ্চিত করুন',
    'auth.registerButton': 'অ্যাকাউন্ট তৈরি করুন',
    'auth.haveAccount': 'ইতিমধ্যে অ্যাকাউন্ট আছে?',

    // Dashboard
    'dash.welcome': 'স্বাগতম',
    'dash.overview': 'ড্যাশবোর্ড ওভারভিউ',
    'dash.financialSummary': 'আর্থিক সারাংশ',
    'dash.kpi': 'মূল কর্মক্ষমতা সূচক',
    'dash.revenue': 'মোট আয়',
    'dash.profit': 'নিট মুনাফা',
    'dash.activeLedgers': 'সক্রিয় লেজার',
    'dash.stockValue': 'স্টক ভ্যালু',
    'dash.activeUsers': 'সক্রিয় ব্যবহারকারী',
    'dash.newOrders': 'নতুন অর্ডার',
    'dash.pendingTasks': 'পেন্ডিং কাজ',
    'dash.recentActivity': 'সাম্প্রতিক কার্যক্রম',
    'dash.recentTransactions': 'সাম্প্রতিক লেনদেন',
    'dash.viewAll': 'সব দেখুন',
    'dash.viewDaybook': 'ডেবুক দেখুন',
    'dash.quickActions': 'দ্রুত অ্যাকশন',
    'dash.voucher': 'ভাউচার',
    'dash.item': 'আইটেম',
    'dash.ledger': 'লেজার',
    'dash.godown': 'গোডাউন',
    'dash.users': 'ব্যবহারকারী',
    'dash.revenueTrajectory': 'রাজস্ব গতিপথ',
    'dash.expenseDistribution': 'ব্যয় বন্টন',
    'dash.netProfitMargin': 'নিট মুনাফার মার্জিন',
    'dash.cashFlowProjection': 'ক্যাশ ফ্লো প্রজেকশন',
    'dash.gateway': 'গেটওয়ে',
    'dash.gatewayOf': 'গেটওয়ে অফ',
    'dash.technicalOverview': 'প্রযুক্তিগত ওভারভিউ',
    'dash.financialYear': 'আর্থিক বছর',
    'dash.from': 'থেকে',
    'dash.to': 'পর্যন্ত',
    'dash.trialPeriod': 'ট্রায়াল পিরিয়ড',
    'dash.subscriptionActive': 'সাবস্ক্রিপশন সক্রিয়',
    'dash.subscriptionInactive': 'সাবস্ক্রিপশন নিষ্ক্রিয়',
    'dash.plan': 'প্ল্যান',
    'dash.daysRemaining': 'দিন বাকি',
    'dash.expiresOn': 'মেয়াদ শেষ হবে',
    'dash.notSet': 'সেট করা হয়নি',
    'dash.renewPlan': 'প্ল্যান নবায়ন করুন',
    'dash.monthlySalesTrend': 'মাসিক বিক্রয়ের প্রবণতা',
    'dash.performanceMetrics': 'কর্মক্ষমতা মেট্রিক্স',
    'dash.revenueTarget': 'রাজস্ব লক্ষ্য',
    'dash.profitMargin': 'মুনাফার মার্জিন',
    'dash.stockTurnover': 'স্টক টার্নওভার',
    'dash.collectionEfficiency': 'সংগ্রহের দক্ষতা',
    'dash.support': 'সাপোর্ট',
    'dash.documentation': 'ডকুমেন্টেশন',
    'dash.systemStatus': 'সিস্টেম স্ট্যাটাস',
    'dash.online': 'অনলাইন',
    'dash.noRecentTransactions': 'কোন সাম্প্রতিক লেনদেন নেই',

    // Settings
    'settings.title': 'সেটিংস',
    'settings.systemSettings': 'সিস্টেম সেটিংস',
    'settings.configureEnvironment': 'আপনার ইআরপি এনভায়রনমেন্ট কনফিগার করুন',
    'settings.profile': 'প্রোফাইল সেটিংস',
    'settings.language': 'ভাষা',
    'settings.selectLanguage': 'ভাষা নির্বাচন করুন',
    'settings.notifications': 'নোটিফিকেশন',
    'settings.security': 'নিরাপত্তা',
    'settings.save': 'পরিবর্তন সংরক্ষণ করুন',
    'settings.companyInfo': 'কোম্পানির তথ্য',
    'settings.uiCustomization': 'UI কাস্টমাইজেশন',
    'settings.reportSettings': 'রিপোর্ট সেটিংস',
    'settings.voucherSettings': 'ভাউচার সেটিংস',
    'settings.printSettings': 'প্রিন্ট সেটিংস',
    'settings.f11Features': 'F11 ফিচারসমূহ',
    'settings.whatsappTemplates': 'হোয়াটসঅ্যাপ টেমপ্লেট',
    'settings.shortcuts': 'শর্টকাট',
    'settings.backupExport': 'ব্যাকআপ ও এক্সপোর্ট',
    'settings.integrations': 'ইন্টিগ্রেশন',
    'settings.voucherConfiguration': 'ভাউচার কনফিগারেশন',
    'settings.referenceNoFormat': 'রেফারেন্স নং ডিফল্ট ফরম্যাট',
    'settings.fieldVisibility': 'ফিল্ড ভিজিবিলিটি',
    'settings.showFreeQty': 'ফ্রি কোয়ান্টিটি দেখান',
    'settings.showFreeQtyDesc': 'ভাউচারে ফ্রি কোয়ান্টিটি কলাম সক্রিয়/নিষ্ক্রিয় করুন।',
    'settings.showDiscPercent': 'ডিসকাউন্ট % দেখান',
    'settings.showDiscPercentDesc': 'ডিসকাউন্ট শতাংশ কলাম সক্রিয়/নিষ্ক্রিয় করুন।',
    'settings.showTaxPercent': 'ট্যাক্স % দেখান',
    'settings.showTaxPercentDesc': 'ট্যাক্স শতাংশ কলাম সক্রিয়/নিষ্ক্রিয় করুন।',
    'settings.theme': 'থিম নির্বাচন করুন',
    'settings.uiStyle': 'UI স্টাইল',
    'settings.layoutWidth': 'লেআউট প্রস্থ',
    'settings.sidebarExpanded': 'ডিফল্টভাবে সাইডবার প্রসারিত',
    'settings.menuBarStyle': 'মেনু বার স্টাইল',
    'settings.glassBackground': 'গ্লাস ব্যাকগ্রাউন্ড ইফেক্ট',
    'settings.notificationAnimation': 'নোটিফিকেশন অ্যানিমেশন',

    // Common
    'common.loading': 'লোড হচ্ছে...',
    'common.error': 'একটি ত্রুটি ঘটেছে',
    'common.success': 'সফল হয়েছে',
    'common.cancel': 'বাতিল',
    'common.delete': 'মুছে ফেলুন',
    'common.edit': 'সম্পাদনা',
    'common.save': 'সংরক্ষণ',
    'common.refresh': 'রিফ্রেশ',
    'common.search': 'অনুসন্ধান',
    'common.filter': 'ফিল্টার',
    'common.actions': 'অ্যাকশন',
    'common.date': 'তারিখ',
    'common.amount': 'পরিমাণ',
    'common.status': 'অবস্থা',
    'common.type': 'ধরণ',
    'common.particulars': 'বিবরণ',
    'common.voucherNo': 'ভাউচার নং'
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('app_language');
    return (saved as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app_language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
