import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'bn';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, variables?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navbar
    'nav.home': 'Home',
    'nav.features': 'Features',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.signIn': 'Sign In',
    'nav.getStarted': 'Get Started',
    'nav.dashboard': 'Dashboard',
    'nav.logout': 'Logout Session',
    'nav.settings': 'Settings',
    'nav.profile': 'Profile',
    'nav.founderPanel': 'Founder Panel',
    'nav.masters': 'Masters',
    'nav.createLedger': 'Create Ledger',
    'nav.createItem': 'Create Item',
    'nav.godowns': 'Godowns',
    'nav.employeeMaster': 'Employee Master',
    'nav.chartOfAccounts': 'Chart of Accounts',
    'nav.itemMaster': 'Item Master',
    'nav.transactions': 'Transactions',
    'nav.voucherEntry': 'Voucher Entry',
    'nav.payroll': 'Payroll',
    'nav.payrollManagement': 'Payroll Management',
    'nav.production': 'Production',
    'nav.orderManagement': 'Order Management',
    'nav.machineManagement': 'Machine Management',
    'nav.productionReports': 'Production Reports',
    'nav.reports': 'Reports',
    'nav.daybook': 'Daybook',
    'nav.balanceSheet': 'Balance Sheet',
    'nav.trialBalance': 'Trial Balance',
    'nav.profitAndLoss': 'Profit & Loss',
    'nav.ratioAnalysis': 'Ratio Analysis',
    'nav.financialInsights': 'Financial Insights',
    'nav.stockSummary': 'Stock Summary',
    'nav.ledgerStatement': 'Ledger Statement',
    'nav.salesPerformance': 'Sales Performance',
    'nav.companyInfo': 'Company Info',
    'nav.uiCustomization': 'UI Customization',
    'nav.voucherSettings': 'Voucher Settings',
    'nav.printSettings': 'Print Settings',
    'nav.f11Features': 'F11 Features',
    'nav.security': 'Security',
    'nav.notifications': 'Notifications',
    'nav.whatsappTemplates': 'WhatsApp Templates',
    'nav.utilities': 'Utilities',
    'nav.companyManagement': 'Company Management',
    'nav.notesMemo': 'Notes / Memo',
    'nav.userManagement': 'User Management',
    'nav.menu': 'Menu',
    'nav.theme': 'Select Theme',

    // Home
    'home.heroTitle': 'Manage Your Business With Intelligence',
    'home.heroSubtitle': 'The all-in-one ERP solution for modern enterprises. Streamline operations, gain real-time insights, and scale your business with confidence.',
    'home.startTrial': 'Start Free Trial',
    'home.viewFeatures': 'View Features',
    'home.statsClients': 'Active Clients',
    'home.statsUptime': 'Uptime Rate',
    'home.statsSupport': 'Expert Support',
    'home.statsExperience': 'Years Experience',
    'home.featuresTitle': 'Everything You Need',
    'home.featuresSubtitle': 'Powerful tools to help you manage every aspect of your business from a single, unified platform.',
    'home.feature1Title': 'Financial Insights',
    'home.feature1Desc': 'Real-time reporting and analytics to help you make data-driven decisions.',
    'home.feature2Title': 'Inventory Control',
    'home.feature2Desc': 'Track stock levels, manage warehouses, and optimize your supply chain.',
    'home.feature3Title': 'Team Collaboration',
    'home.feature3Desc': 'Manage employees, payroll, and permissions with ease.',
    'home.feature4Title': 'Enterprise Security',
    'home.feature4Desc': 'Bank-grade security to keep your sensitive business data safe.',
    'home.feature5Title': 'Fast Performance',
    'home.feature5Desc': 'Optimized for speed to ensure your business never slows down.',
    'home.feature6Title': 'Cloud Access',
    'home.feature6Desc': 'Access your business data from anywhere in the world, on any device.',
    'home.ctaTitle': 'Ready to Transform Your Business?',
    'home.ctaSubtitle': 'Join hundreds of successful companies already using our ERP system to power their growth.',
    'home.getStarted': 'Get Started Now',

    // Footer
    'footer.description': 'A comprehensive ERP solution designed to streamline your business operations, from inventory management to financial reporting.',
    'footer.product': 'Product',
    'footer.legal': 'Legal',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',

    // Auth
    'auth.signInTitle': 'Sign in to ERP System',
    'auth.signInSubtitle': 'Enter your details below to access your account.',
    'auth.email': 'Email Address',
    'auth.password': 'Password',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.signInButton': 'Sign In',
    'auth.noAccount': "Don't have an account?",
    'auth.createAccount': 'Create one',
    'auth.registerTitle': 'Create your Account',
    'auth.registerSubtitle': 'Join us today and start managing your business smarter.',
    'auth.fullName': 'Full Name',
    'auth.confirmPassword': 'Confirm Password',
    'auth.registerButton': 'Create Account',
    'auth.haveAccount': 'Already have an account?',

    // Dashboard
    'dash.welcome': 'Welcome back',
    'dash.overview': 'Dashboard Overview',
    'dash.financialSummary': 'Financial Summary',
    'dash.kpi': 'Key Performance Indicators',
    'dash.revenue': 'Total Revenue',
    'dash.profit': 'Net Profit',
    'dash.activeLedgers': 'Active Ledgers',
    'dash.stockValue': 'Stock Value',
    'dash.activeUsers': 'Active Users',
    'dash.newOrders': 'New Orders',
    'dash.pendingTasks': 'Pending Tasks',
    'dash.recentActivity': 'Recent Activity',
    'dash.recentTransactions': 'Recent Transactions',
    'dash.viewAll': 'View All',
    'dash.viewDaybook': 'View Daybook',
    'dash.quickActions': 'Quick Actions',
    'dash.voucher': 'Voucher',
    'dash.item': 'Item',
    'dash.ledger': 'Ledger',
    'dash.godown': 'Godown',
    'dash.users': 'Users',
    'dash.revenueTrajectory': 'Revenue Trajectory',
    'dash.expenseDistribution': 'Expense Distribution',
    'dash.netProfitMargin': 'Net Profit Margin',
    'dash.cashFlowProjection': 'Cash Flow Projection',
    'dash.gateway': 'Gateway',
    'dash.gatewayOf': 'Gateway of',
    'dash.technicalOverview': 'Technical Overview',
    'dash.financialYear': 'Financial Year',
    'dash.from': 'From',
    'dash.to': 'To',
    'dash.trialPeriod': 'Trial Period',
    'dash.subscriptionActive': 'Subscription Active',
    'dash.subscriptionInactive': 'Subscription Inactive',
    'dash.plan': 'Plan',
    'dash.daysRemaining': 'days remaining',
    'dash.expiresOn': 'Expires On',
    'dash.notSet': 'Not Set',
    'dash.renewPlan': 'Renew Plan',
    'dash.monthlySalesTrend': 'Monthly Sales Trend',
    'dash.performanceMetrics': 'Performance Metrics',
    'dash.revenueTarget': 'Revenue Target',
    'dash.profitMargin': 'Profit Margin',
    'dash.stockTurnover': 'Stock Turnover',
    'dash.collectionEfficiency': 'Collection Efficiency',
    'dash.support': 'Support',
    'dash.documentation': 'Documentation',
    'dash.systemStatus': 'System Status',
    'dash.online': 'Online',
    'dash.noRecentTransactions': 'No recent transactions',

    // Item
    'item.title': 'Item Master',
    'item.new': 'New Item',
    'item.edit': 'Edit Item',
    'item.name': 'Item Name',
    'item.category': 'Category',
    'item.partNo': 'Part No',
    'item.description': 'Description',
    'item.unit': 'Unit',
    'item.openingQty': 'Opening Qty',
    'item.openingRate': 'Opening Rate',
    'item.hasBatches': 'Maintain Batches',
    'item.hasExpiry': 'Maintain Expiry',
    'item.barcode': 'Barcode',
    'item.lowStockThreshold': 'Low Stock Threshold',
    'item.taxPercent': 'Tax %',
    'item.schemeQty': 'Scheme Qty',
    'item.schemeFreeQty': 'Scheme Free Qty',
    'item.generalDetails': 'General Details',
    'item.namePlaceholder': 'e.g., iPhone 15 Pro, Cement Bag',
    'item.categoryPlaceholder': 'e.g., Electronics, Construction',
    'item.partNoPlaceholder': 'e.g., SKU-123',
    'item.unitPlaceholder': 'Select Unit',
    'item.openingQtyPlaceholder': '0.00',
    'item.openingRatePlaceholder': '0.00',
    'item.barcodePlaceholder': 'Scan or enter barcode',
    'item.taxPercentPlaceholder': '0',
    'item.stockSettings': 'Stock & Tracking Settings',
    'item.maintainBatches': 'Maintain Batches',
    'item.maintainExpiry': 'Maintain Expiry',
    'item.lowStockPlaceholder': '0',
    'item.deleteWarning': 'This item has existing transactions in the system. Deleting it will cause inconsistencies in your financial reports.',
    'item.deleteConfirmText': 'Are you sure you want to delete "{name}"? This item will be permanently removed from your inventory.',
    'item.recommendKeep': 'It is highly recommended to keep this item.',

    // Ledger
    'ledger.title': 'Ledger Master',
    'ledger.new': 'New Ledger',
    'ledger.edit': 'Edit Ledger',
    'ledger.name': 'Ledger Name',
    'ledger.alias': 'Alias',
    'ledger.group': 'Under Group',
    'ledger.openingBalance': 'Opening Balance',
    'ledger.mailingDetails': 'Mailing Details',
    'ledger.address': 'Address',
    'ledger.division': 'Division',
    'ledger.country': 'Country',
    'ledger.postalCode': 'Postal Code',
    'ledger.mobile': 'Mobile No',
    'ledger.email': 'Email',
    'ledger.website': 'Website',
    'ledger.contactDetails': 'Contact Details',
    'ledger.bankDetails': 'Bank Details',
    'ledger.billWise': 'Maintain Bill-wise',
    'ledger.vatNo': 'VAT No',
    'ledger.generalDetails': 'General Details',
    'ledger.namePlaceholder': 'e.g., Company Name',
    'ledger.aliasPlaceholder': 'Alternative name',
    'ledger.under': 'Under (Group)',
    'ledger.billByBill': 'Maintain balances bill-by-bill',
    'ledger.costCenters': 'Cost Centers are applicable',
    'ledger.interestCalculation': 'Activate interest calculation',
    'ledger.provideContactDetails': 'Provide Contact Details',
    'ledger.contactPerson': 'Contact Person Name',
    'ledger.phone': 'Phone No.',
    'ledger.provideBankDetails': 'Provide Bank Details',
    'ledger.transactionType': 'Transaction Type',
    'ledger.cheque': 'Cheque',
    'ledger.eFundTransfer': 'e-fund Transfer',
    'ledger.other': 'Other',
    'ledger.accountNo': 'A/c No.',
    'ledger.bankCode': 'Bank Code (IFSC/Swift)',
    'ledger.bankName': 'Bank Name',
    'ledger.recommendKeep': 'It is highly recommended to keep this ledger.',
    'ledger.deleteWarning': 'This ledger has existing transactions in the system. Deleting it will cause inconsistencies in your financial reports.',
    'ledger.deleteConfirmText': 'Are you sure you want to delete "{name}"? This ledger will be permanently removed from your chart of accounts.',

    // Settings
    'settings.title': 'Settings',
    'settings.systemSettings': 'System Settings',
    'settings.configureEnvironment': 'Configure your ERP environment',
    'settings.profile': 'Profile Settings',
    'settings.language': 'Language',
    'settings.selectLanguage': 'Select Language',
    'settings.notifications': 'Notifications',
    'settings.security': 'Security',
    'settings.save': 'Save Changes',
    'settings.companyInfo': 'Company Information',
    'settings.uiCustomization': 'UI Customization',
    'settings.reportSettings': 'Report Settings',
    'settings.voucherSettings': 'Voucher Settings',
    'settings.printSettings': 'Print Settings',
    'settings.f11Features': 'F11 Features',
    'settings.whatsappTemplates': 'WhatsApp Templates',
    'settings.shortcuts': 'Shortcuts',
    'settings.backupExport': 'Backup & Export',
    'settings.integrations': 'Integrations',
    'settings.voucherConfiguration': 'Voucher Configuration',
    'settings.referenceNoFormat': 'Reference No. Default Format',
    'settings.fieldVisibility': 'Field Visibility',
    'settings.showFreeQty': 'Show Free Quantity',
    'settings.showFreeQtyDesc': 'Enable/Disable Free Quantity column in vouchers.',
    'settings.showDiscPercent': 'Show Discount %',
    'settings.showDiscPercentDesc': 'Enable/Disable Discount percentage column.',
    'settings.showTaxPercent': 'Show Tax %',
    'settings.showTaxPercentDesc': 'Enable/Disable Tax percentage column.',
    'settings.theme': 'Select Theme',
    'settings.uiStyle': 'UI Style',
    'settings.layoutWidth': 'Layout Width',
    'settings.sidebarExpanded': 'Sidebar Expanded by Default',
    'settings.menuBarStyle': 'Menu Bar Style',
    'settings.glassBackground': 'Glass Background Effect',
    'settings.notificationAnimation': 'Notification Animation',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'An error occurred',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.save': 'Save',
    'common.refresh': 'Refresh',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.actions': 'Actions',
    'common.date': 'Date',
    'common.amount': 'Amount',
    'common.status': 'Status',
    'common.type': 'Type',
    'common.particulars': 'Particulars',
    'common.voucherNo': 'Voucher No.',
    'common.creation': 'Creation',
    'common.alteration': 'Alteration',
    'common.update': 'Update',
    'common.create': 'Create',
    'common.confirmDeletion': 'Confirm Deletion',
    'common.cannotUndone': 'This action cannot be undone',
    'common.warning': 'Warning',
    'common.confirmDelete': 'Confirm Delete',

    // Features Page
    'features.title': 'Powerful Features for Modern Enterprises',
    'features.subtitle': 'Explore the comprehensive suite of tools designed to help your business operate more efficiently and grow faster.',
    'features.feature1Title': 'Financial Management',
    'features.feature1Desc': 'Complete control over your finances with real-time reporting, automated bookkeeping, and advanced analytics.',
    'features.feature1Detail1': 'Automated Balance Sheets',
    'features.feature1Detail2': 'Profit & Loss Statements',
    'features.feature1Detail3': 'Real-time Cash Flow Tracking',
    'features.feature1Detail4': 'Multi-currency Support',
    'features.feature2Title': 'Inventory & Warehouse',
    'features.feature2Desc': 'Manage your stock levels across multiple locations, optimize reordering, and track every item in your supply chain.',
    'features.feature2Detail1': 'Multi-godown Management',
    'features.feature2Detail2': 'Batch & Expiry Tracking',
    'features.feature2Detail3': 'Automated Stock Alerts',
    'features.feature2Detail4': 'Barcode Integration',
    'features.feature3Title': 'Production & Manufacturing',
    'features.feature3Desc': 'Streamline your manufacturing process from order to delivery with integrated production planning and machine management.',
    'features.feature3Detail1': 'Order Management',
    'features.feature3Detail2': 'Machine Efficiency Tracking',
    'features.feature3Detail3': 'Production Reports',
    'features.feature3Detail4': 'Resource Allocation',
    'features.feature4Title': 'Payroll & HR',
    'features.feature4Desc': 'Manage your most valuable asset—your people. Handle payroll, attendance, and employee records in one place.',
    'features.feature4Detail1': 'Automated Salary Sheets',
    'features.feature4Detail2': 'Employee Master Records',
    'features.feature4Detail3': 'Attendance Tracking',
    'features.feature4Detail4': 'Performance Analytics',
    'features.moreTitle': 'And Much More',
    'features.moreSubtitle': 'Every detail considered for your business success.',
    'features.extra1Title': 'Data Security',
    'features.extra1Desc': 'Your data is encrypted and backed up daily.',
    'features.extra2Title': 'Instant Sync',
    'features.extra2Desc': 'Real-time updates across all your devices.',
    'features.extra3Title': 'Custom Printing',
    'features.extra3Desc': 'Design and print invoices, reports, and more.',
    'features.extra4Title': 'Global Access',
    'features.extra4Desc': 'Secure access from any browser, anywhere.',
    'features.extra5Title': 'Ratio Analysis',
    'features.extra5Desc': 'Advanced financial health indicators.',
    'features.extra6Title': 'Growth Tracking',
    'features.extra6Desc': 'Monitor your business progress over time.',
    'features.extra7Title': 'Voucher Entry',
    'features.extra7Desc': 'Simplified accounting for non-accountants.',
    'features.extra8Title': 'User Roles',
    'features.extra8Desc': 'Granular permission control for your team.',

    // About Page
    'about.missionTitle': 'Our Mission',
    'about.missionDesc': 'We are dedicated to empowering businesses of all sizes with the tools they need to thrive in a digital-first world. Our goal is to simplify complex operations and provide clarity through intelligent data.',
    'about.bannerTitle': 'Built for Business',
    'about.bannerSubtitle': 'Founded in 2010, serving over 500+ companies worldwide.',
    'about.leadershipTitle': 'Our Leadership',
    'about.value1Title': 'Innovation',
    'about.value1Desc': "We constantly push the boundaries of what's possible in ERP technology.",
    'about.value2Title': 'Customer First',
    'about.value2Desc': "Our customers' success is our primary metric for our own success.",
    'about.value3Title': 'Global Reach',
    'about.value3Desc': 'Supporting businesses across continents with localized solutions.',
    'about.value4Title': 'Excellence',
    'about.value4Desc': 'We strive for perfection in every line of code and every support interaction.',

    // Contact Page
    'contact.title': 'Get in Touch',
    'contact.subtitle': "Have questions? We're here to help. Send us a message and our team will get back to you within 24 hours.",
    'contact.emailLabel': 'Email Us',
    'contact.phoneLabel': 'Call Us',
    'contact.phone2': 'Mon-Fri, 9am-6pm EST',
    'contact.addressLabel': 'Visit Our Office',
    'contact.fullName': 'Full Name',
    'contact.fullNamePlaceholder': 'John Doe',
    'contact.emailAddress': 'Email Address',
    'contact.emailPlaceholder': 'john@example.com',
    'contact.subject': 'Subject',
    'contact.subjectPlaceholder': 'How can we help?',
    'contact.message': 'Message',
    'contact.messagePlaceholder': 'Tell us more about your needs...',
    'contact.sendMessage': 'Send Message'
  },
  bn: {
    // Navbar
    'nav.home': 'হোম',
    'nav.features': 'বৈশিষ্ট্য',
    'nav.about': 'আমাদের সম্পর্কে',
    'nav.contact': 'যোগাযোগ',
    'nav.signIn': 'লগইন',
    'nav.getStarted': 'শুরু করুন',
    'nav.dashboard': 'ড্যাশবোর্ড',
    'nav.logout': 'লগআউট সেশন',
    'nav.settings': 'সেটিংস',
    'nav.profile': 'প্রোফাইল',
    'nav.founderPanel': 'ফাউন্ডার প্যানেল',
    'nav.masters': 'মাস্টার্স',
    'nav.createLedger': 'লেজার তৈরি করুন',
    'nav.createItem': 'আইটেম তৈরি করুন',
    'nav.godowns': 'গোডাউন',
    'nav.employeeMaster': 'কর্মচারী মাস্টার',
    'nav.chartOfAccounts': 'চার্ট অফ অ্যাকাউন্টস',
    'nav.itemMaster': 'আইটেম মাস্টার',
    'nav.transactions': 'লেনদেন',
    'nav.voucherEntry': 'ভাউচার এন্ট্রি',
    'nav.payroll': 'পেরোল',
    'nav.payrollManagement': 'পেরোল ম্যানেজমেন্ট',
    'nav.production': 'উৎপাদন',
    'nav.orderManagement': 'অর্ডার ম্যানেজমেন্ট',
    'nav.machineManagement': 'মেশিন ম্যানেজমেন্ট',
    'nav.productionReports': 'উৎপাদন রিপোর্ট',
    'nav.reports': 'রিপোর্ট',
    'nav.daybook': 'ডে-বুক',
    'nav.balanceSheet': 'ব্যালেন্স শিট',
    'nav.trialBalance': 'ট্রায়াল ব্যালেন্স',
    'nav.profitAndLoss': 'লাভ ও ক্ষতি',
    'nav.ratioAnalysis': 'অনুপাত বিশ্লেষণ',
    'nav.financialInsights': 'আর্থিক অন্তর্দৃষ্টি',
    'nav.stockSummary': 'স্টক সারাংশ',
    'nav.ledgerStatement': 'লেজার স্টেটমেন্ট',
    'nav.salesPerformance': 'বিক্রয় কর্মক্ষমতা',
    'nav.companyInfo': 'কোম্পানির তথ্য',
    'nav.uiCustomization': 'UI কাস্টমাইজেশন',
    'nav.voucherSettings': 'ভাউচার সেটিংস',
    'nav.printSettings': 'প্রিন্ট সেটিংস',
    'nav.f11Features': 'F11 ফিচারসমূহ',
    'nav.security': 'নিরাপত্তা',
    'nav.notifications': 'নোটিফিকেশন',
    'nav.whatsappTemplates': 'হোয়াটসঅ্যাপ টেমপ্লেট',
    'nav.utilities': 'ইউটিলিটিস',
    'nav.companyManagement': 'কোম্পানি ম্যানেজমেন্ট',
    'nav.notesMemo': 'নোট / মেমো',
    'nav.userManagement': 'ব্যবহারকারী ম্যানেজমেন্ট',
    'nav.menu': 'মেনু',
    'nav.theme': 'থিম নির্বাচন করুন',

    // Home
    'home.heroTitle': 'বুদ্ধিমত্তার সাথে আপনার ব্যবসা পরিচালনা করুন',
    'home.heroSubtitle': 'আধুনিক এন্টারপ্রাইজের জন্য অল-ইন-ওয়ান ইআরপি সমাধান। অপারেশন সহজ করুন, রিয়েল-টাইম ইনসাইট পান এবং আত্মবিশ্বাসের সাথে আপনার ব্যবসা বৃদ্ধি করুন।',
    'home.startTrial': 'ফ্রি ট্রায়াল শুরু করুন',
    'home.viewFeatures': 'বৈশিষ্ট্য দেখুন',
    'home.statsClients': 'সক্রিয় ক্লায়েন্ট',
    'home.statsUptime': 'আপটাইম রেট',
    'home.statsSupport': 'বিশেষজ্ঞ সাপোর্ট',
    'home.statsExperience': 'বছরের অভিজ্ঞতা',
    'home.featuresTitle': 'আপনার যা কিছু প্রয়োজন',
    'home.featuresSubtitle': 'একটি একক প্ল্যাটফর্ম থেকে আপনার ব্যবসার প্রতিটি দিক পরিচালনা করতে সাহায্য করার জন্য শক্তিশালী টুলস।',
    'home.feature1Title': 'আর্থিক অন্তর্দৃষ্টি',
    'home.feature1Desc': 'আপনাকে ডেটা-চালিত সিদ্ধান্ত নিতে সাহায্য করার জন্য রিয়েল-টাইম রিপোর্টিং এবং বিশ্লেষণ।',
    'home.feature2Title': 'ইনভেন্টরি নিয়ন্ত্রণ',
    'home.feature2Desc': 'স্টক লেভেল ট্র্যাক করুন, গুদাম পরিচালনা করুন এবং আপনার সাপ্লাই চেইন অপ্টিমাইজ করুন।',
    'home.feature3Title': 'টিম সহযোগিতা',
    'home.feature3Desc': 'সহজেই কর্মচারী, বেতন এবং অনুমতি পরিচালনা করুন।',
    'home.feature4Title': 'এন্টারপ্রাইজ নিরাপত্তা',
    'home.feature4Desc': 'আপনার সংবেদনশীল ব্যবসায়িক ডেটা নিরাপদ রাখতে ব্যাংক-গ্রেড নিরাপত্তা।',
    'home.feature5Title': 'দ্রুত পারফরম্যান্স',
    'home.feature5Desc': 'আপনার ব্যবসা যাতে কখনও ধীর না হয় তা নিশ্চিত করতে গতির জন্য অপ্টিমাইজ করা হয়েছে।',
    'home.feature6Title': 'ক্লাউড অ্যাক্সেস',
    'home.feature6Desc': 'যেকোনো ডিভাইস থেকে বিশ্বের যেকোনো প্রান্ত থেকে আপনার ব্যবসায়িক ডেটা অ্যাক্সেস করুন।',
    'home.ctaTitle': 'আপনার ব্যবসা পরিবর্তন করতে প্রস্তুত?',
    'home.ctaSubtitle': 'শত শত সফল কোম্পানির সাথে যোগ দিন যারা ইতিমধ্যে তাদের ব্যবসার প্রবৃদ্ধির জন্য আমাদের ইআরপি সিস্টেম ব্যবহার করছে।',
    'home.getStarted': 'এখনই শুরু করুন',

    // Footer
    'footer.description': 'একটি ব্যাপক ইআরপি সমাধান যা আপনার ব্যবসার কার্যক্রমকে সহজতর করার জন্য ডিজাইন করা হয়েছে, ইনভেন্টরি ম্যানেজমেন্ট থেকে শুরু করে আর্থিক রিপোর্টিং পর্যন্ত।',
    'footer.product': 'পণ্য',
    'footer.legal': 'আইনি',
    'footer.privacy': 'গোপনীয়তা নীতি',
    'footer.terms': 'পরিষেবার শর্তাবলী',

    // Auth
    'auth.signInTitle': 'ইআরপি সিস্টেমে সাইন ইন করুন',
    'auth.signInSubtitle': 'আপনার অ্যাকাউন্টে প্রবেশ করতে নিচে আপনার বিবরণ দিন।',
    'auth.email': 'ইমেইল ঠিকানা',
    'auth.password': 'পাসওয়ার্ড',
    'auth.forgotPassword': 'পাসওয়ার্ড ভুলে গেছেন?',
    'auth.signInButton': 'সাইন ইন',
    'auth.noAccount': "অ্যাকাউন্ট নেই?",
    'auth.createAccount': 'একটি তৈরি করুন',
    'auth.registerTitle': 'আপনার অ্যাকাউন্ট তৈরি করুন',
    'auth.registerSubtitle': 'আজই আমাদের সাথে যোগ দিন এবং স্মার্টলি আপনার ব্যবসা পরিচালনা শুরু করুন।',
    'auth.fullName': 'পুরো নাম',
    'auth.confirmPassword': 'পাসওয়ার্ড নিশ্চিত করুন',
    'auth.registerButton': 'অ্যাকাউন্ট তৈরি করুন',
    'auth.haveAccount': 'ইতিমধ্যে অ্যাকাউন্ট আছে?',

    // Dashboard
    'dash.welcome': 'স্বাগতম',
    'dash.overview': 'ড্যাশবোর্ড ওভারভিউ',
    'dash.financialSummary': 'আর্থিক সারাংশ',
    'dash.kpi': 'মূল কর্মক্ষমতা সূচক',
    'dash.revenue': 'মোট আয়',
    'dash.profit': 'নিট মুনাফা',
    'dash.activeLedgers': 'সক্রিয় লেজার',
    'dash.stockValue': 'স্টক ভ্যালু',
    'dash.activeUsers': 'সক্রিয় ব্যবহারকারী',
    'dash.newOrders': 'নতুন অর্ডার',
    'dash.pendingTasks': 'পেন্ডিং কাজ',
    'dash.recentActivity': 'সাম্প্রতিক কার্যক্রম',
    'dash.recentTransactions': 'সাম্প্রতিক লেনদেন',
    'dash.viewAll': 'সব দেখুন',
    'dash.viewDaybook': 'ডেবুক দেখুন',
    'dash.quickActions': 'দ্রুত অ্যাকশন',
    'dash.voucher': 'ভাউচার',
    'dash.item': 'আইটেম',
    'dash.ledger': 'লেজার',
    'dash.godown': 'গোডাউন',
    'dash.users': 'ব্যবহারকারী',
    'dash.revenueTrajectory': 'রাজস্ব গতিপথ',
    'dash.expenseDistribution': 'ব্যয় বন্টন',
    'dash.netProfitMargin': 'নিট মুনাফার মার্জিন',
    'dash.cashFlowProjection': 'ক্যাশ ফ্লো প্রজেকশন',
    'dash.gateway': 'গেটওয়ে',
    'dash.gatewayOf': 'গেটওয়ে অফ',
    'dash.technicalOverview': 'প্রযুক্তিগত ওভারভিউ',
    'dash.financialYear': 'আর্থিক বছর',
    'dash.from': 'থেকে',
    'dash.to': 'পর্যন্ত',
    'dash.trialPeriod': 'ট্রায়াল পিরিয়ড',
    'dash.subscriptionActive': 'সাবস্ক্রিপশন সক্রিয়',
    'dash.subscriptionInactive': 'সাবস্ক্রিপশন নিষ্ক্রিয়',
    'dash.plan': 'প্ল্যান',
    'dash.daysRemaining': 'দিন বাকি',
    'dash.expiresOn': 'মেয়াদ শেষ হবে',
    'dash.notSet': 'সেট করা হয়নি',
    'dash.renewPlan': 'প্ল্যান নবায়ন করুন',
    'dash.monthlySalesTrend': 'মাসিক বিক্রয়ের প্রবণতা',
    'dash.performanceMetrics': 'কর্মক্ষমতা মেট্রিক্স',
    'dash.revenueTarget': 'রাজস্ব লক্ষ্য',
    'dash.profitMargin': 'মুনাফার মার্জিন',
    'dash.stockTurnover': 'স্টক টার্নওভার',
    'dash.collectionEfficiency': 'সংগ্রহের দক্ষতা',
    'dash.support': 'সাপোর্ট',
    'dash.documentation': 'ডকুমেন্টেশন',
    'dash.systemStatus': 'সিস্টেম স্ট্যাটাস',
    'dash.online': 'অনলাইন',
    'dash.noRecentTransactions': 'কোন সাম্প্রতিক লেনদেন নেই',

    // Item
    'item.title': 'আইটেম মাস্টার',
    'item.new': 'নতুন আইটেম',
    'item.edit': 'আইটেম সম্পাদনা',
    'item.name': 'আইটেমের নাম',
    'item.category': 'ক্যাটাগরি',
    'item.partNo': 'পার্ট নং',
    'item.description': 'বিবরণ',
    'item.unit': 'ইউনিট',
    'item.openingQty': 'প্রারম্ভিক পরিমাণ',
    'item.openingRate': 'প্রারম্ভিক হার',
    'item.hasBatches': 'ব্যাচ মেইনটেইন করুন',
    'item.hasExpiry': 'মেয়াদ শেষ মেইনটেইন করুন',
    'item.barcode': 'বারকোড',
    'item.lowStockThreshold': 'লো স্টক থ্রেশহোল্ড',
    'item.taxPercent': 'ট্যাক্স %',
    'item.schemeQty': 'স্কিম পরিমাণ',
    'item.schemeFreeQty': 'স্কিম ফ্রি পরিমাণ',
    'item.generalDetails': 'সাধারণ বিবরণ',
    'item.namePlaceholder': 'যেমন: আইফোন ১৫ প্রো, সিমেন্ট ব্যাগ',
    'item.categoryPlaceholder': 'যেমন: ইলেকট্রনিক্স, নির্মাণ',
    'item.partNoPlaceholder': 'যেমন: SKU-১২৩',
    'item.unitPlaceholder': 'ইউনিট নির্বাচন করুন',
    'item.openingQtyPlaceholder': '০.০০',
    'item.openingRatePlaceholder': '০.০০',
    'item.barcodePlaceholder': 'বারকোড স্ক্যান করুন বা লিখুন',
    'item.taxPercentPlaceholder': '০',
    'item.stockSettings': 'স্টক ও ট্র্যাকিং সেটিংস',
    'item.maintainBatches': 'ব্যাচ মেইনটেইন করুন',
    'item.maintainExpiry': 'মেয়াদ শেষ মেইনটেইন করুন',
    'item.lowStockPlaceholder': '০',
    'item.deleteWarning': 'এই আইটেমটির সিস্টেমে বিদ্যমান লেনদেন রয়েছে। এটি মুছে ফেললে আপনার আর্থিক রিপোর্টে অসঙ্গতি দেখা দেবে।',
    'item.deleteConfirmText': 'আপনি কি নিশ্চিত যে আপনি "{name}" মুছে ফেলতে চান? এই আইটেমটি আপনার ইনভেন্টরি থেকে স্থায়ীভাবে সরিয়ে ফেলা হবে।',
    'item.recommendKeep': 'এই আইটেমটি রাখা অত্যন্ত সুপারিশ করা হয়।',

    // Ledger
    'ledger.title': 'লেজার মাস্টার',
    'ledger.new': 'নতুন লেজার',
    'ledger.edit': 'লেজার সম্পাদনা',
    'ledger.name': 'লেজারের নাম',
    'ledger.alias': 'অ্যালিয়াস',
    'ledger.group': 'গ্রুপের অধীনে',
    'ledger.openingBalance': 'প্রারম্ভিক ব্যালেন্স',
    'ledger.mailingDetails': 'মেইলিং বিবরণ',
    'ledger.address': 'ঠিকানা',
    'ledger.division': 'বিভাগ',
    'ledger.country': 'দেশ',
    'ledger.postalCode': 'পোস্টাল কোড',
    'ledger.mobile': 'মোবাইল নং',
    'ledger.email': 'ইমেইল',
    'ledger.website': 'ওয়েবসাইট',
    'ledger.contactDetails': 'যোগাযোগের বিবরণ',
    'ledger.bankDetails': 'ব্যাংক বিবরণ',
    'ledger.billWise': 'বিল-ভিত্তিক মেইনটেইন করুন',
    'ledger.vatNo': 'ভ্যাট নং',
    'ledger.generalDetails': 'সাধারণ বিবরণ',
    'ledger.namePlaceholder': 'যেমন: কোম্পানির নাম',
    'ledger.aliasPlaceholder': 'বিকল্প নাম',
    'ledger.under': 'গ্রুপের অধীনে',
    'ledger.billByBill': 'বিল-বাই-বিল ব্যালেন্স মেইনটেইন করুন',
    'ledger.costCenters': 'কস্ট সেন্টার প্রযোজ্য',
    'ledger.interestCalculation': 'সুদ গণনা সক্রিয় করুন',
    'ledger.provideContactDetails': 'যোগাযোগের বিবরণ দিন',
    'ledger.contactPerson': 'যোগাযোগকারীর নাম',
    'ledger.phone': 'ফোন নং',
    'ledger.provideBankDetails': 'ব্যাংক বিবরণ দিন',
    'ledger.transactionType': 'লেনদেনের ধরণ',
    'ledger.cheque': 'চেক',
    'ledger.eFundTransfer': 'ই-ফান্ড ট্রান্সফার',
    'ledger.other': 'অন্যান্য',
    'ledger.accountNo': 'অ্যাকাউন্ট নং',
    'ledger.bankCode': 'ব্যাংক কোড (IFSC/Swift)',
    'ledger.bankName': 'ব্যাংকের নাম',
    'ledger.recommendKeep': 'এই লেজারটি রাখা অত্যন্ত সুপারিশ করা হয়।',
    'ledger.deleteWarning': 'এই লেজারটির সিস্টেমে বিদ্যমান লেনদেন রয়েছে। এটি মুছে ফেললে আপনার আর্থিক রিপোর্টে অসঙ্গতি দেখা দেবে।',
    'ledger.deleteConfirmText': 'আপনি কি নিশ্চিত যে আপনি "{name}" মুছে ফেলতে চান? এই লেজারটি আপনার চার্ট অফ অ্যাকাউন্টস থেকে স্থায়ীভাবে সরিয়ে ফেলা হবে।',

    // Settings
    'settings.title': 'সেটিংস',
    'settings.systemSettings': 'সিস্টেম সেটিংস',
    'settings.configureEnvironment': 'আপনার ইআরপি এনভায়রনমেন্ট কনফিগার করুন',
    'settings.profile': 'প্রোফাইল সেটিংস',
    'settings.language': 'ভাষা',
    'settings.selectLanguage': 'ভাষা নির্বাচন করুন',
    'settings.notifications': 'নোটিফিকেশন',
    'settings.security': 'নিরাপত্তা',
    'settings.save': 'পরিবর্তন সংরক্ষণ করুন',
    'settings.companyInfo': 'কোম্পানির তথ্য',
    'settings.uiCustomization': 'UI কাস্টমাইজেশন',
    'settings.reportSettings': 'রিপোর্ট সেটিংস',
    'settings.voucherSettings': 'ভাউচার সেটিংস',
    'settings.printSettings': 'প্রিন্ট সেটিংস',
    'settings.f11Features': 'F11 ফিচারসমূহ',
    'settings.whatsappTemplates': 'হোয়াটসঅ্যাপ টেমপ্লেট',
    'settings.shortcuts': 'শর্টকাট',
    'settings.backupExport': 'ব্যাকআপ ও এক্সপোর্ট',
    'settings.integrations': 'ইন্টিগ্রেশন',
    'settings.voucherConfiguration': 'ভাউচার কনফিগারেশন',
    'settings.referenceNoFormat': 'রেফারেন্স নং ডিফল্ট ফরম্যাট',
    'settings.fieldVisibility': 'ফিল্ড ভিজিবিলিটি',
    'settings.showFreeQty': 'ফ্রি কোয়ান্টিটি দেখান',
    'settings.showFreeQtyDesc': 'ভাউচারে ফ্রি কোয়ান্টিটি কলাম সক্রিয়/নিষ্ক্রিয় করুন।',
    'settings.showDiscPercent': 'ডিসকাউন্ট % দেখান',
    'settings.showDiscPercentDesc': 'ডিসকাউন্ট শতাংশ কলাম সক্রিয়/নিষ্ক্রিয় করুন।',
    'settings.showTaxPercent': 'ট্যাক্স % দেখান',
    'settings.showTaxPercentDesc': 'ট্যাক্স শতাংশ কলাম সক্রিয়/নিষ্ক্রিয় করুন।',
    'settings.theme': 'থিম নির্বাচন করুন',
    'settings.uiStyle': 'UI স্টাইল',
    'settings.layoutWidth': 'লেআউট প্রস্থ',
    'settings.sidebarExpanded': 'ডিফল্টভাবে সাইডবার প্রসারিত',
    'settings.menuBarStyle': 'মেনু বার স্টাইল',
    'settings.glassBackground': 'গ্লাস ব্যাকগ্রাউন্ড ইফেক্ট',
    'settings.notificationAnimation': 'নোটিফিকেশন অ্যানিমেশন',

    // Common
    'common.loading': 'লোড হচ্ছে...',
    'common.error': 'একটি ত্রুটি ঘটেছে',
    'common.success': 'সফল হয়েছে',
    'common.cancel': 'বাতিল',
    'common.delete': 'মুছে ফেলুন',
    'common.edit': 'সম্পাদনা',
    'common.save': 'সংরক্ষণ',
    'common.refresh': 'রিফ্রেশ',
    'common.search': 'অনুসন্ধান',
    'common.filter': 'ফিল্টার',
    'common.actions': 'অ্যাকশন',
    'common.date': 'তারিখ',
    'common.amount': 'পরিমাণ',
    'common.status': 'অবস্থা',
    'common.type': 'ধরণ',
    'common.particulars': 'বিবরণ',
    'common.voucherNo': 'ভাউচার নং',
    'common.creation': 'তৈরি',
    'common.alteration': 'পরিবর্তন',
    'common.update': 'আপডেট',
    'common.create': 'তৈরি করুন',
    'common.confirmDeletion': 'মুছে ফেলার নিশ্চিতকরণ',
    'common.cannotUndone': 'এই কাজটি আর ফিরিয়ে আনা যাবে না',
    'common.warning': 'সতর্কতা',
    'common.confirmDelete': 'মুছা নিশ্চিত করুন',

    // Features Page
    'features.title': 'আধুনিক এন্টারপ্রাইজের জন্য শক্তিশালী বৈশিষ্ট্য',
    'features.subtitle': 'আপনার ব্যবসাকে আরও দক্ষতার সাথে পরিচালনা করতে এবং দ্রুত বৃদ্ধি করতে সাহায্য করার জন্য ডিজাইন করা সরঞ্জামগুলির ব্যাপক সেটটি অন্বেষণ করুন।',
    'features.feature1Title': 'আর্থিক ব্যবস্থাপনা',
    'features.feature1Desc': 'রিয়েল-টাইম রিপোর্টিং, স্বয়ংক্রিয় বুককিপিং এবং উন্নত বিশ্লেষণের মাধ্যমে আপনার অর্থের ওপর পূর্ণ নিয়ন্ত্রণ।',
    'features.feature1Detail1': 'স্বয়ংক্রিয় ব্যালেন্স শিট',
    'features.feature1Detail2': 'লাভ ও ক্ষতির বিবরণ',
    'features.feature1Detail3': 'রিয়েল-টাইম ক্যাশ ফ্লো ট্র্যাকিং',
    'features.feature1Detail4': 'মাল্টি-কারেন্সি সাপোর্ট',
    'features.feature2Title': 'ইনভেন্টরি ও গুদাম',
    'features.feature2Desc': 'একাধিক অবস্থানে আপনার স্টক লেভেল পরিচালনা করুন, রিঅর্ডারিং অপ্টিমাইজ করুন এবং আপনার সাপ্লাই চেইনের প্রতিটি আইটেম ট্র্যাক করুন।',
    'features.feature2Detail1': 'মাল্টি-গোডাউন ম্যানেজমেন্ট',
    'features.feature2Detail2': 'ব্যাচ ও মেয়াদ ট্র্যাকিং',
    'features.feature2Detail3': 'স্বয়ংক্রিয় স্টক অ্যালার্ট',
    'features.feature2Detail4': 'বারকোড ইন্টিগ্রেশন',
    'features.feature3Title': 'উৎপাদন ও ম্যানুফ্যাকচারিং',
    'features.feature3Desc': 'অর্ডার থেকে ডেলিভারি পর্যন্ত আপনার ম্যানুফ্যাকচারিং প্রক্রিয়াকে সমন্বিত উৎপাদন পরিকল্পনা এবং মেশিন ম্যানেজমেন্টের মাধ্যমে সহজতর করুন।',
    'features.feature3Detail1': 'অর্ডার ম্যানেজমেন্ট',
    'features.feature3Detail2': 'মেশিন দক্ষতা ট্র্যাকিং',
    'features.feature3Detail3': 'উৎপাদন রিপোর্ট',
    'features.feature3Detail4': 'রিসোর্স অ্যালোকেশন',
    'features.feature4Title': 'পেরোল ও এইচআর',
    'features.feature4Desc': 'আপনার সবচেয়ে মূল্যবান সম্পদ—আপনার কর্মীদের পরিচালনা করুন। বেতন, উপস্থিতি এবং কর্মচারীদের রেকর্ড এক জায়গায় হ্যান্ডেল করুন।',
    'features.feature4Detail1': 'স্বয়ংক্রিয় স্যালারি শিট',
    'features.feature4Detail2': 'কর্মচারী মাস্টার রেকর্ড',
    'features.feature4Detail3': 'উপস্থিতি ট্র্যাকিং',
    'features.feature4Detail4': 'পারফরম্যান্স অ্যানালিটিক্স',
    'features.moreTitle': 'এবং আরও অনেক কিছু',
    'features.moreSubtitle': 'আপনার ব্যবসার সাফল্যের জন্য প্রতিটি বিবরণ বিবেচনা করা হয়েছে।',
    'features.extra1Title': 'ডেটা নিরাপত্তা',
    'features.extra1Desc': 'আপনার ডেটা এনক্রিপ্ট করা এবং প্রতিদিন ব্যাকআপ নেওয়া হয়।',
    'features.extra2Title': 'তাত্ক্ষণিক সিঙ্ক',
    'features.extra2Desc': 'আপনার সমস্ত ডিভাইস জুড়ে রিয়েল-টাইম আপডেট।',
    'features.extra3Title': 'কাস্টম প্রিন্টিং',
    'features.extra3Desc': 'ইনভয়েস, রিপোর্ট এবং আরও অনেক কিছু ডিজাইন ও প্রিন্ট করুন।',
    'features.extra4Title': 'গ্লোবাল অ্যাক্সেস',
    'features.extra4Desc': 'যেকোনো ব্রাউজার থেকে, যেকোনো জায়গা থেকে নিরাপদ অ্যাক্সেস।',
    'features.extra5Title': 'অনুপাত বিশ্লেষণ',
    'features.extra5Desc': 'উন্নত আর্থিক স্বাস্থ্য নির্দেশক।',
    'features.extra6Title': 'প্রবৃদ্ধি ট্র্যাকিং',
    'features.extra6Desc': 'সময়ের সাথে সাথে আপনার ব্যবসার অগ্রগতি পর্যবেক্ষণ করুন।',
    'features.extra7Title': 'ভাউচার এন্ট্রি',
    'features.extra7Desc': 'অ-অ্যাকাউন্ট্যান্টদের জন্য সরলীকৃত অ্যাকাউন্টিং।',
    'features.extra8Title': 'ব্যবহারকারীর ভূমিকা',
    'features.extra8Desc': 'আপনার টিমের জন্য দানাদার অনুমতি নিয়ন্ত্রণ।',

    // About Page
    'about.missionTitle': 'আমাদের লক্ষ্য',
    'about.missionDesc': 'আমরা ডিজিটাল-প্রথম বিশ্বে উন্নতির জন্য প্রয়োজনীয় সরঞ্জামগুলির মাধ্যমে সব আকারের ব্যবসাকে ক্ষমতায়ন করতে নিবেদিত। আমাদের লক্ষ্য হলো জটিল ক্রিয়াকলাপগুলিকে সহজ করা এবং বুদ্ধিমান ডেটার মাধ্যমে স্বচ্ছতা প্রদান করা।',
    'about.bannerTitle': 'ব্যবসার জন্য নির্মিত',
    'about.bannerSubtitle': '২০১০ সালে প্রতিষ্ঠিত, বিশ্বজুড়ে ৫০০+ এরও বেশি কোম্পানিকে সেবা দিচ্ছে।',
    'about.leadershipTitle': 'আমাদের নেতৃত্ব',
    'about.value1Title': 'উদ্ভাবন',
    'about.value1Desc': 'আমরা ইআরপি প্রযুক্তিতে যা সম্ভব তার সীমানা ক্রমাগত প্রসারিত করছি।',
    'about.value2Title': 'গ্রাহক প্রথম',
    'about.value2Desc': 'আমাদের গ্রাহকদের সাফল্যই আমাদের নিজস্ব সাফল্যের প্রাথমিক মাপকাঠি।',
    'about.value3Title': 'গ্লোবাল রিচ',
    'about.value3Desc': 'স্থানীয় সমাধানের মাধ্যমে মহাদেশ জুড়ে ব্যবসা সমর্থন করা।',
    'about.value4Title': 'উৎকর্ষ',
    'about.value4Desc': 'আমরা কোডের প্রতিটি লাইন এবং প্রতিটি সাপোর্ট ইন্টারঅ্যাকশনে নিখুঁততার জন্য চেষ্টা করি।',

    // Contact Page
    'contact.title': 'যোগাযোগ করুন',
    'contact.subtitle': 'প্রশ্ন আছে? আমরা সাহায্য করতে এখানে আছি। আমাদের একটি বার্তা পাঠান এবং আমাদের টিম ২৪ ঘন্টার মধ্যে আপনার সাথে যোগাযোগ করবে।',
    'contact.emailLabel': 'আমাদের ইমেইল করুন',
    'contact.phoneLabel': 'আমাদের কল করুন',
    'contact.phone2': 'সোম-শুক্র, সকাল ৯টা - সন্ধ্যা ৬টা EST',
    'contact.addressLabel': 'আমাদের অফিস ভিজিট করুন',
    'contact.fullName': 'পুরো নাম',
    'contact.fullNamePlaceholder': 'জন ডো',
    'contact.emailAddress': 'ইমেইল ঠিকানা',
    'contact.emailPlaceholder': 'john@example.com',
    'contact.subject': 'বিষয়',
    'contact.subjectPlaceholder': 'আমরা কীভাবে সাহায্য করতে পারি?',
    'contact.message': 'বার্তা',
    'contact.messagePlaceholder': 'আপনার প্রয়োজন সম্পর্কে আমাদের আরও বলুন...',
    'contact.sendMessage': 'বার্তা পাঠান'
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('app_language');
    return (saved as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app_language', lang);
  };

  const t = (key: string, variables?: Record<string, string | number>): string => {
    let translation = translations[language][key] || key;
    if (variables) {
      Object.entries(variables).forEach(([k, v]) => {
        translation = translation.replace(`{${k}}`, String(v));
      });
    }
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
