import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'bn';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, variables?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navbar
    'nav.home': 'Home',
    'nav.features': 'Features',
    'nav.pricing': 'Pricing',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.signIn': 'Sign In',
    'nav.getStarted': 'Get Started',
    'nav.dashboard': 'Dashboard',
    'nav.logout': 'Logout Session',
    'nav.settings': 'Settings',
    'nav.profile': 'Profile',
    'nav.founderPanel': 'Founder Panel',
    'nav.masters': 'Masters',
    'nav.createLedger': 'Create Ledger',
    'nav.createItem': 'Create Item',
    'nav.godowns': 'Godowns',
    'nav.employeeMaster': 'Employee Master',
    'nav.chartOfAccounts': 'Chart of Accounts',
    'nav.itemMaster': 'Item Master',
    'nav.alter': 'Alter',
    'nav.transactions': 'Transactions',
    'nav.voucherEntry': 'Voucher Entry',
    'nav.payroll': 'Payroll',
    'nav.payrollManagement': 'Payroll Management',
    'nav.production': 'Production',
    'nav.orderManagement': 'Order Management',
    'nav.machineManagement': 'Machine Management',
    'nav.productionReports': 'Production Reports',
    'nav.reports': 'Reports',
    'daybook.title': 'Daybook',
    'daybook.loading': 'Loading transactions...',
    'daybook.noTransactions': 'No transactions recorded',
    'daybook.noTransactionsPeriod': 'No transactions recorded for this period',
    'daybook.viewDaybook': 'View Daybook',
    'daybook.detailed': 'Detailed',
    'daybook.condensed': 'Condensed',
    'daybook.showNarration': 'Show Narration',
    'daybook.showInventory': 'Show Inventory Details',
    'daybook.showEnteredBy': 'Show Entered By',
    'daybook.sortingMethod': 'Sorting Method',
    'daybook.downloadExcel': 'Download Excel',
    'daybook.downloadPDF': 'Download PDF',
    'daybook.configureReport': 'Configure Report',
    'nav.balanceSheet': 'Balance Sheet',
    'nav.trialBalance': 'Trial Balance',
    'nav.profitAndLoss': 'Profit & Loss',
    'nav.ratioAnalysis': 'Ratio Analysis',
    'nav.financialInsights': 'Financial Insights',
    'nav.stockSummary': 'Stock Summary',
    'nav.ledgerStatement': 'Ledger Statement',
    'nav.accountBooks': 'Account Books',
    'nav.inventoryBooks': 'Inventory Books',
    'nav.statementOfInventory': 'Statement of Inventory',
    'nav.statementOfInventoryShort': 'Statement of Inventory',
    'nav.payrollReports': 'Payroll Reports',
    'nav.negativeLedger': 'Negative Ledger',
    'nav.negativeStock': 'Negative Stock',
    'nav.salesPerformance': 'Sales Performance',
    'nav.companyInfo': 'Company Info',
    'nav.uiCustomization': 'UI Customization',
    'nav.voucherSettings': 'Voucher Settings',
    'nav.printSettings': 'Print Settings',
    'nav.f11Features': 'F11 Features',
    'nav.security': 'Security',
    'nav.notifications': 'Notifications',
    'nav.whatsappTemplates': 'WhatsApp Templates',
    'nav.utilities': 'Utilities',
    'nav.companyManagement': 'Company Management',
    'nav.notesMemo': 'Notes / Memo',
    'nav.userManagement': 'User Management',
    'nav.menu': 'Menu',
    'nav.theme': 'Select Theme',
    'nav.daybook': 'Daybook',
    'nav.subscription': 'Subscription',
    'subscription.title': 'Subscription Management',
    'subscription.subtitle': 'Manage your plan, view billing history, and upgrade your features.',
    'subscription.usageLimits': 'Usage Limits',
    'subscription.upgradePlan': 'Upgrade Plan',
    'subscription.currentSubscription': 'Current Subscription',
    'subscription.planType': 'Plan Type',
    'subscription.expiryDate': 'Expiry Date',
    'subscription.price': 'Price',
    'subscription.featuresIncluded': 'Features Included:',
    'subscription.orderHistory': 'Order History',
    'subscription.needHelp': 'Need Help?',
    'subscription.needHelpDesc': 'If you have any issues with your subscription or need a custom plan for your business, please contact our support team.',
    'subscription.paymentMethods': 'Payment Methods',
    'subscription.paymentMethodsDesc': 'Currently we only support manual bank transfers and mobile banking (bKash/Nagad).',
    'common.vouchers': 'Vouchers',
    'common.items': 'Items',
    'common.ledgers': 'Ledgers',
    'common.users': 'Users',
    'common.godowns': 'Godowns',
    'common.employees': 'Employees',

    // Home
    'home.heroTitle': 'Manage Your Business With Intelligence',
    'home.heroSubtitle': 'The all-in-one ERP solution for modern enterprises. Streamline operations, gain real-time insights, and scale your business with confidence.',
    'home.startTrial': 'Start Free Trial',
    'home.viewFeatures': 'View Features',
    'home.statsClients': 'Active Clients',
    'home.statsClientsVal': '500+',
    'home.statsUptime': 'Uptime Rate',
    'home.statsUptimeVal': '99.9%',
    'home.statsSupport': 'Expert Support',
    'home.statsSupportVal': '24/7',
    'home.statsExperience': 'Years Experience',
    'home.statsExperienceVal': '15+',
    'home.featuresTitle': 'Everything You Need',
    'home.featuresSubtitle': 'Powerful tools to help you manage every aspect of your business from a single, unified platform.',
    'home.feature1Title': 'Financial Insights',
    'home.feature1Desc': 'Real-time reporting and analytics to help you make data-driven decisions.',
    'home.feature2Title': 'Inventory Control',
    'home.feature2Desc': 'Track stock levels, manage warehouses, and optimize your supply chain.',
    'home.feature3Title': 'Team Collaboration',
    'home.feature3Desc': 'Manage employees, payroll, and permissions with ease.',
    'home.feature4Title': 'Enterprise Security',
    'home.feature4Desc': 'Bank-grade security to keep your sensitive business data safe.',
    'home.feature5Title': 'Fast Performance',
    'home.feature5Desc': 'Optimized for speed to ensure your business never slows down.',
    'home.feature6Title': 'Cloud Access',
    'home.feature6Desc': 'Access your business data from anywhere in the world, on any device.',
    'home.ctaTitle': 'Ready to Transform Your Business?',
    'home.ctaSubtitle': 'Join hundreds of successful companies already using our ERP system to power their growth.',
    'home.getStarted': 'Get Started Now',

    // Footer
    'footer.description': 'A comprehensive ERP solution designed to streamline your business operations, from inventory management to financial reporting.',
    'footer.product': 'Product',
    'footer.legal': 'Legal',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',

    // Auth
    'auth.signInTitle': 'Sign in to ERP System',
    'auth.signInSubtitle': 'Enter your details below to access your account.',
    'auth.email': 'Email Address',
    'auth.password': 'Password',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.signInButton': 'Sign In',
    'auth.noAccount': "Don't have an account?",
    'auth.createAccount': 'Create one',
    'auth.registerTitle': 'Create your Account',
    'auth.registerSubtitle': 'Join us today and start managing your business smarter.',
    'auth.fullName': 'Full Name',
    'auth.confirmPassword': 'Confirm Password',
    'auth.registerButton': 'Create Account',
    'auth.haveAccount': 'Already have an account?',

    // Dashboard
    'dash.welcome': 'Welcome back',
    'dash.overview': 'Dashboard Overview',
    'dash.financialSummary': 'Financial Summary',
    'dash.kpi': 'Key Performance Indicators',
    'dash.revenue': 'Total Revenue',
    'dash.profit': 'Net Profit',
    'dash.activeLedgers': 'Active Ledgers',
    'dash.stockValue': 'Stock Value',
    'dash.activeUsers': 'Active Users',
    'dash.newOrders': 'New Orders',
    'dash.pendingTasks': 'Pending Tasks',
    'dash.recentActivity': 'Recent Activity',
    'dash.recentTransactions': 'Recent Transactions',
    'dash.viewAll': 'View All',
    'dash.viewDaybook': 'View Daybook',
    'dash.quickActions': 'Quick Actions',
    'dash.voucher': 'Voucher',
    'dash.item': 'Item',
    'dash.ledger': 'Ledger',
    'dash.godown': 'Godown',
    'dash.users': 'Users',
    'dash.revenueTrajectory': 'Revenue Trajectory',
    'dash.expenseDistribution': 'Expense Distribution',
    'dash.netProfitMargin': 'Net Profit Margin',
    'dash.cashFlowProjection': 'Cash Flow Projection',
    'dash.gateway': 'Gateway',
    'dash.gatewayOf': 'Gateway of',
    'dash.technicalOverview': 'Technical Overview',
    'dash.financialYear': 'Financial Year',
    'dash.from': 'From',
    'dash.to': 'To',
    'dash.trialPeriod': 'Trial Period',
    'dash.subscriptionActive': 'Subscription Active',
    'dash.subscriptionInactive': 'Subscription Inactive',
    'dash.plan': 'Plan',
    'dash.daysRemaining': 'days remaining',
    'dash.expiresOn': 'Expires On',
    'dash.notSet': 'Not Set',
    'dash.renewPlan': 'Renew Plan',
    'dash.monthlySalesTrend': 'Monthly Sales Trend',
    'dash.performanceMetrics': 'Performance Metrics',
    'dash.revenueTarget': 'Revenue Target',
    'dash.profitMargin': 'Profit Margin',
    'dash.stockTurnover': 'Stock Turnover',
    'dash.collectionEfficiency': 'Collection Efficiency',
    'dash.support': 'Support',
    'dash.documentation': 'Documentation',
    'dash.systemStatus': 'System Status',
    'dash.online': 'Online',
    'dash.noRecentTransactions': 'No recent transactions',

    // Item
    'item.title': 'Item Master',
    'item.new': 'New Item',
    'item.edit': 'Edit Item',
    'item.name': 'Item Name',
    'item.category': 'Category',
    'item.partNo': 'Part No',
    'item.description': 'Description',
    'item.descriptionPlaceholder': 'Enter item description...',
    'item.unit': 'Unit',
    'item.openingQty': 'Opening Qty',
    'item.openingRate': 'Opening Rate',
    'item.hasBatches': 'Maintain Batches',
    'item.hasExpiry': 'Maintain Expiry',
    'item.barcode': 'Barcode',
    'item.lowStockThreshold': 'Low Stock Threshold',
    'item.taxPercent': 'Tax %',
    'item.generalItems': 'General Items',
    'item.schemeQty': 'Scheme Qty',
    'item.schemeFreeQty': 'Scheme Free Qty',
    'item.generalDetails': 'General Details',
    'item.namePlaceholder': 'e.g., iPhone 15 Pro, Cement Bag',
    'item.categoryPlaceholder': 'e.g., Electronics, Construction',
    'item.partNoPlaceholder': 'e.g., SKU-123',
    'item.unitPlaceholder': 'Select Unit',
    'item.openingQtyPlaceholder': '0.00',
    'item.openingRatePlaceholder': '0.00',
    'item.barcodePlaceholder': 'Scan or enter barcode',
    'item.taxPercentPlaceholder': '0',
    'item.addNewCategory': 'Add New Category',
    'item.stockSettings': 'Stock & Tracking Settings',
    'item.maintainBatches': 'Maintain Batches',
    'item.maintainExpiry': 'Maintain Expiry',
    'item.lowStockPlaceholder': '0',
    'item.deleteWarning': 'This item has existing transactions in the system. Deleting it will cause inconsistencies in your financial reports.',
    'item.deleteConfirmText': 'Are you sure you want to delete "{name}"? This item will be permanently removed from your inventory.',
    'item.recommendKeep': 'It is highly recommended to keep this item.',
    'item.masterView': 'Master View',
    'item.priceList': 'Price List',
    'item.recalculateStats': 'Recalculate Stats',
    'item.createNewItem': 'Create New Item',
    'item.searchPlaceholder': 'SEARCH BY NAME OR PART NO...',
    'item.totalItems': 'Total Items',
    'item.loadingInventory': 'Loading Inventory...',
    'item.noItemsFound': 'No items found matching your criteria',
    'item.standardPrice': 'Standard Price',
    'item.wholesalePrice': 'Wholesale Price',
    'item.retailPrice': 'Retail Price',
    'item.avgCost': 'Avg Cost',
    'item.currentStock': 'Current Stock',
    'production.productionControl': 'Production Control',
    'production.newOrder': 'New Order',
    'production.idle': 'System Idle',
    'production.processingJob': 'Processing Print Job',
    'production.readyForAssignment': 'Ready for Assignment',
    'production.searchPlaceholder': 'Search Client / Item / Design...',
    'production.noMachinesConfigured': 'No machines configured. Add machines in settings.',
    'production.statusUpdateSuccess': 'Order status updated to {status}',
    'production.statusUpdateError': 'Failed to update status',
    'production.status.Pending': 'Pending',
    'production.status.Printing': 'Printing',
    'production.status.Completed': 'Completed',
    'production.status.Delivered': 'Delivered',
    'production.status.Cancelled': 'Cancelled',
    'stock.title': 'Stock Summary',
    'stock.loading': 'Loading stock data...',
    'stock.noItems': 'No stock items matching search',
    'stock.allGodowns': 'All Godowns',
    'stock.lowStockOnly': 'Low Stock Only',
    'stock.valuationMethod': 'Valuation Method',
    'stock.weightedAvg': 'Weighted Average',
    'stock.quickCreateItem': 'Quick Create Item',
    'stock.searchPlaceholder': 'Search items or categories...',
    'stock.recalculate': 'Recalculate',
    'stock.lowStock': 'Low Stock',
    'reports.financial': 'Financial Reports',
    'reports.cashBankBook': 'Cash/Bank Book',
    'reports.groupSummary': 'Group Summary',
    'reports.itemMonthly': 'Item Monthly Summary',
    'reports.movementAnalysis': 'Movement Analysis',
    'reports.stockQuery': 'Stock Query',
    'reports.balanceSheet': 'Balance Sheet',
    'reports.profitAndLoss': 'Profit & Loss A/c',
    'reports.trialBalance': 'Trial Balance',
    'reports.asOnDate': 'As on Date',
    'reports.liabilities': 'Liabilities',
    'reports.assets': 'Assets',
    'reports.totalLiabilities': 'Total Liabilities',
    'reports.totalAssets': 'Total Assets',
    'reports.closingStock': 'Closing Stock',
    'reports.netProfit': 'Net Profit',
    'reports.netLoss': 'Net Loss',
    'reports.grossProfit': 'Gross Profit',
    'reports.grossLoss': 'Gross Loss',
    'reports.openingStock': 'Opening Stock',
    'reports.purchases': 'Purchases',
    'reports.sales': 'Sales',
    'reports.directExpenses': 'Direct Expenses',
    'reports.directIncomes': 'Direct Incomes',
    'reports.indirectExpenses': 'Indirect Expenses',
    'reports.indirectIncomes': 'Indirect Incomes',
    'reports.differenceInOpening': 'Difference in Opening Balances',
    'reports.debit': 'Debit',
    'reports.credit': 'Credit',
    'reports.openingBalance': 'Opening Balance',
    'reports.closingBalance': 'Closing Balance',
    'reports.tradingAccount': 'Trading Account',
    'reports.incomeStatement': 'Income Statement',
    'accounts.chartOfAccounts': 'Chart of Accounts',
    'accounts.hierarchy': 'Hierarchy of Ledgers and Groups',
    'accounts.noLedgersInGroup': 'No ledgers in this group',
    'accounts.loadingHierarchy': 'Loading Hierarchy...',
    'ledger.statement': 'Ledger Statement',
    'ledger.selectToView': 'Please select a ledger to view statement',
    'ledger.loadingEntries': 'Loading entries...',
    'ledger.noTransactions': 'No transactions found for this period',
    'ledger.vchType': 'Vch Type',
    'ledger.vchNo': 'Vch No.',
    'ledger.openingBalance': 'Opening Balance',
    'ledger.closingBalance': 'Closing Balance',
    'ledger.runningBalance': 'Running Balance',
    'ledger.particulars': 'Particulars',
    'ledger.searchLedgers': 'Search ledgers...',
    'godown.title': 'Godown / Location Master',
    'godown.add': 'Add Godown',
    'godown.edit': 'Edit Godown',
    'godown.name': 'Godown Name',
    'godown.location': 'Location / Address',
    'godown.contactPerson': 'Contact Person',
    'godown.phoneNumber': 'Phone Number',
    'godown.description': 'Description',
    'godown.deleteConfirm': 'Are you sure you want to delete this godown?',
    'godown.saveSuccess': 'Godown saved successfully',
    'godown.updateSuccess': 'Godown updated successfully',
    'godown.deleteSuccess': 'Godown deleted successfully',
    'godown.noGodowns': 'No godowns found. Create one to get started.',
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.backToLogin': 'Back to Login',
    'auth.sendResetLink': 'Send Reset Link',
    'auth.resetSent': 'Reset link sent! Check your email.',
    'auth.companyName': 'Company Name',
    'auth.alreadyHaveAccount': 'Already have an account?',
    'auth.loggingIn': 'Logging in...',
    'auth.registering': 'Registering...',
    'auth.sending': 'Sending...',
    'company.title': 'Company Management',
    'company.subtitle': 'Manage your business entities and switch between them.',
    'company.create': 'Create New Company',
    'company.edit': 'Edit Company',
    'company.name': 'Company Name',
    'company.logo': 'Logo URL',
    'company.switch': 'Switch',
    'company.current': 'Current',
    'company.createSuccess': 'New company created and switched successfully!',
    'company.switchSuccess': 'Switched company successfully!',
    'company.updateSuccess': 'Company updated successfully!',
    'company.deleteSuccess': 'Company deleted successfully!',
    'company.noCompanies': 'No companies found.',
    'employee.title': 'Employee Master',
    'employee.subtitle': 'Manage your workforce and employee details.',
    'employee.add': 'Add Employee',
    'employee.edit': 'Edit Employee',
    'employee.name': 'Employee Name',
    'employee.designation': 'Designation',
    'employee.department': 'Department',
    'employee.bloodGroup': 'Blood Group',
    'employee.presentAddress': 'Present Address',
    'employee.permanentAddress': 'Permanent Address',
    'employee.nidNumber': 'NID Number',
    'employee.drivingLicense': 'Driving License',
    'employee.passportNo': 'Passport No',
    'employee.bankName': 'Bank Name',
    'employee.bankBranch': 'Bank Branch',
    'employee.bankAccount': 'Account Number',
    'employee.bankRouting': 'Routing Number',
    'employee.emergencyContact': 'Emergency Contact',
    'employee.emergencyRelation': 'Relation',
    'employee.emergencyPhone': 'Emergency Phone',
    'employee.joiningDate': 'Joining Date',
    'employee.salary': 'Salary',
    'employee.status': 'Status',
    'employee.active': 'Active',
    'employee.inactive': 'Inactive',
    'employee.createSuccess': 'Employee saved successfully',
    'employee.updateSuccess': 'Employee updated successfully',
    'employee.deleteSuccess': 'Employee deleted successfully',
    'employee.deleteConfirm': 'Are you sure you want to delete this employee?',
    'employee.noEmployees': 'No employees found.',
    'employee.identification': 'Identification',
    'employee.addressDetails': 'Address Details',
    'employee.bankDetails': 'Bank Account Details',
    'employee.onLeave': 'On Leave',
    'employee.selectGroup': 'Select Group',
    'employee.saveData': 'Save Employee Data',
    'employee.contactName': 'Contact Name',
    'employee.branchName': 'Branch Name',

    // Ledger
    'ledger.title': 'Ledger Master',
    'ledger.new': 'New Ledger',
    'ledger.edit': 'Edit Ledger',
    'ledger.name': 'Ledger Name',
    'ledger.alias': 'Alias',
    'ledger.group': 'Under Group',
    'ledger.mailingDetails': 'Mailing Details',
    'ledger.address': 'Address',
    'ledger.division': 'Division',
    'ledger.country': 'Country',
    'ledger.postalCode': 'Postal Code',
    'ledger.mobile': 'Mobile No',
    'ledger.email': 'Email',
    'ledger.website': 'Website',
    'ledger.contactDetails': 'Contact Details',
    'ledger.bankDetails': 'Bank Details',
    'ledger.bankingDetails': 'Banking Details',
    'ledger.billWise': 'Maintain Bill-wise',
    'ledger.vatNo': 'VAT No',
    'ledger.generalDetails': 'General Details',
    'ledger.namePlaceholder': 'e.g., Company Name',
    'ledger.aliasPlaceholder': 'Alternative name',
    'ledger.under': 'Under (Group)',
    'ledger.billByBill': 'Maintain balances bill-by-bill',
    'ledger.costCenters': 'Cost Centers are applicable',
    'ledger.interestCalculation': 'Activate interest calculation',
    'ledger.provideContactDetails': 'Provide Contact Details',
    'ledger.contactPerson': 'Contact Person Name',
    'ledger.phone': 'Phone No.',
    'ledger.provideBankDetails': 'Provide Bank Details',
    'ledger.transactionType': 'Transaction Type',
    'ledger.cheque': 'Cheque',
    'ledger.eFundTransfer': 'e-fund Transfer',
    'ledger.other': 'Other',
    'ledger.accountNo': 'A/c No.',
    'ledger.bankCode': 'Bank Code (IFSC/Swift)',
    'ledger.bankName': 'Bank Name',
    'ledger.recommendKeep': 'It is highly recommended to keep this ledger.',
    'ledger.deleteWarning': 'This ledger has existing transactions in the system. Deleting it will cause inconsistencies in your financial reports.',
    'ledger.deleteConfirmText': 'Are you sure you want to delete "{name}"? This ledger will be permanently removed from your chart of accounts.',
    'ledger.creditLimit': 'Credit Limit',

    // Settings
    'settings.title': 'Settings',
    'settings.systemSettings': 'System Settings',
    'settings.configureEnvironment': 'Configure your ERP environment',
    'settings.profile': 'Profile Settings',
    'settings.language': 'Language',
    'settings.selectLanguage': 'Select Language',
    'settings.notifications': 'Notifications',
    'settings.security': 'Security',
    'settings.save': 'Save Changes',
    'settings.companyInfo': 'Company Information',
    'settings.companyName': 'Company Name',
    'settings.companyLogo': 'Company Logo',
    'settings.removeLogo': 'Remove Logo',
    'settings.companySlogan': 'Company Slogan',
    'settings.companyAddress': 'Company Address',
    'settings.financialYearStart': 'Financial Year Start',
    'settings.reportSettings': 'Report Settings',
    'settings.reportLayoutStyle': 'Report Layout Style',
    'settings.uiCustomization': 'UI Customization',
    'settings.menuBarStyle': 'Menu Bar Style',
    'settings.classicSidebar': 'Classic Sidebar (Default)',
    'settings.ribbonStyle': 'Microsoft Office Ribbon',
    'settings.macosStyle': 'macOS Top Menu Bar',
    'settings.windows11Style': 'Windows 11 Taskbar Style',
    'settings.menuBarStyleDesc': 'Choose your preferred navigation layout.',
    'settings.layoutWidth': 'Layout Width',
    'settings.fullResponsive': 'Full Responsive (Dashboard Style)',
    'settings.constrainedWidth': 'Founder Panel Style (Max 7xl)',
    'settings.layoutWidthDesc': 'Choose how wide the application content should be.',
    'settings.uiStyle': 'UI/UX Style',
    'settings.uiStyleClassic': 'UI/UX 1 (Classic)',
    'settings.uiStyleModern': 'UI/UX 2 (Modern Colorized)',
    'settings.uiStyleGlass': 'UI/UX 3 (Glassmorphism macOS)',
    'settings.uiStyleDesc': 'Choose the overall UI/UX style for the application.',
    'settings.dashboardDesign': 'Dashboard Design Style',
    'settings.dashboardDesignClassic': 'Design 1 (Classic Tally Style)',
    'settings.dashboardDesignModern': 'Design 2 (Modern Colorful Dashboard)',
    'settings.dashboardDesignDesc': 'Choose the visual style for your main dashboard.',
    'settings.showRunningBalance': 'Show Running Balance in Reports',
    'settings.showRunningBalanceDesc': 'Enable running balance column in ledger statements by default.',
    'settings.showMobileNav': 'Show Mobile Navigation Bar',
    'settings.showMobileNavDesc': 'Enable top navigation bar with Back/Forward buttons for mobile apps.',
    'settings.voucherSettings': 'Voucher Settings',
    'settings.printSettings': 'Print Settings',
    'settings.f11Features': 'F11 Features',
    'settings.whatsappTemplates': 'WhatsApp Templates',
    'settings.shortcuts': 'Shortcuts',
    'settings.backupExport': 'Backup & Export',
    'settings.integrations': 'Integrations',
    'settings.voucherConfiguration': 'Voucher Configuration',
    'settings.referenceNoFormat': 'Reference No. Default Format',
    'settings.fieldVisibility': 'Field Visibility',
    'settings.showFreeQty': 'Show Free Quantity',
    'settings.showFreeQtyDesc': 'Enable/Disable Free Quantity column in vouchers.',
    'settings.showDiscPercent': 'Show Discount %',
    'settings.showDiscPercentDesc': 'Enable/Disable Discount percentage column.',
    'settings.showTaxPercent': 'Show Tax %',
    'settings.showTaxPercentDesc': 'Enable/Disable Tax percentage column.',
    'settings.theme': 'Select Theme',
    'settings.sidebarExpanded': 'Sidebar Expanded by Default',
    'settings.glassBackground': 'Glass Background Effect',
    'settings.notificationAnimation': 'Notification Animation',
    
    // Common
    'common.loading': 'Loading...',
    'common.from': 'From',
    'common.to': 'To',
    'common.f12Configure': 'F12: Configure',
    'common.excel': 'Excel',
    'common.pdf': 'PDF',
    'common.vchType': 'Vch Type',
    'common.vchNo': 'Vch No.',
    'common.total': 'Total',
    'common.select': 'Select',
    'common.debit': 'Debit',
    'common.credit': 'Credit',
    'common.clearVoucher': 'Clear Voucher',
    'common.csv': 'CSV',
    'common.recalculate': 'Recalculate',
    'common.totalValue': 'Total Value',
    'common.avgRate': 'Avg. Rate',
    'common.value': 'Value',
    'common.grandTotal': 'Grand Total',
    'common.f1Help': 'F1: Help',
    'common.group': 'Group',
    'common.searchPlaceholder': 'Search...',
    'common.noData': 'No data available',
    'common.error': 'An error occurred',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.save': 'Save',
    'common.refresh': 'Refresh',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.actions': 'Actions',
    'common.phone': 'Phone Number',
    'common.date': 'Date',
    'common.amount': 'Amount',
    'common.status': 'Status',
    'common.type': 'Type',
    'common.particulars': 'Particulars',
    'common.voucherNo': 'Voucher No.',
    'common.creation': 'Creation',
    'common.alteration': 'Alteration',
    'alter.groups': 'Groups',
    'alter.ledgers': 'Ledgers',
    'alter.stockItems': 'Stock Items',
    'alter.voucherTypes': 'Voucher Types',
    'alter.stockCategories': 'Stock Category',
    'alter.units': 'Units',
    'alter.locations': 'Godowns',
    'alter.employeeGroups': 'Designation',
    'alter.employees': 'Employees',
    'alter.creditLimit': 'Credit Limit',
    'common.update': 'Update',
    'common.create': 'Create',
    'common.confirmDeletion': 'Confirm Deletion',
    'common.cannotUndone': 'This action cannot be undone',
    'common.warning': 'Warning',
    'common.confirmDelete': 'Confirm Delete',
    'common.voucherType': 'Voucher Type',
    'common.partyName': 'Party Name',
    'common.quick': 'Quick',
    'common.itemName': 'Item Name',
    'common.account': 'Account',
    'common.englishFont': 'English Font',
    'common.banglaFont': 'Bangla Font',
    'common.selectFont': 'Select Font',
    'common.referenceNo': 'Reference No.',
    'common.currency': 'Currency',
    'common.exchangeRate': 'Ex. Rate',
    'common.exchangeRateDesc': 'Exchange Rate: Multiplier to convert transaction currency to base currency.',
    'common.currentBalance': 'Current Balance',
    'common.salesLedger': 'Sales Ledger',
    'common.purchaseLedger': 'Purchase Ledger',
    'common.salesperson': 'Salesperson',
    'common.providedBy': 'Provided by',
    'common.receivedBy': 'Received by',
    'common.godown': 'Godown',
    'common.batch': 'Batch',
    'common.expiry': 'Expiry',
    'common.quantity': 'Quantity',
    'common.free': 'Free',
    'common.rate': 'Rate',
    'common.per': 'per',
    'common.discPercent': 'Disc %',
    'common.taxPercent': 'Tax %',
    'common.addItem': 'Add Item',
    'common.deleteItem': 'Delete Item',
    'common.disc': 'Disc',
    'common.taka': 'TAKA',
    'common.percent': 'Percent',
    'common.tax': 'Tax',
    'common.whatsapp': 'WhatsApp',
    'common.email': 'Email',
    'common.close': 'Close',
    'common.clearVoucherConfirm': 'Are you sure you want to clear all voucher data? This action cannot be undone.',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.basicInfo': 'Basic Information',
    'common.upload': 'Upload',
    'common.of': 'of',
    'common.step': 'Step',
    'common.staff': 'Staff',
    'common.user': 'User',
    'common.switchCompany': 'Switch Company',
    'common.goTo': 'Go To',
    'common.profileNotFound': 'Profile Not Found',
    'common.profileNotFoundDesc': "Your account exists, but we couldn't find your ERP profile. This might happen if your account was created manually or if there was an error during registration.",
    'common.signOutTryAgain': 'Sign Out & Try Again',
    'common.loggedInAs': 'Logged in as',
    'common.erpSystem': 'ERP System',
    'common.logout': 'Logout',
    'common.selectTheme': 'Select Theme',
    'common.allApps': 'All Apps',
    'common.pinnedApps': 'Pinned Apps',
    'common.searchResults': 'Search Results',
    'common.noResultsFound': 'No results found',
    'common.searchAppsPlaceholder': 'Search for apps, settings, and documents',
    'common.placeholderWarning': 'You are currently in a placeholder company. Your data might be in another company.',
    'common.reportsGroupNotFound': 'Reports Group Not Found',
    'common.configureReportsGroup': 'Please configure the Reports group in the Founder Panel.',
    'nav.accounting': 'Accounting',
    'nav.inventory': 'Inventory',
    'nav.exceptionReports': 'Exception Reports',
    'voucher.config': 'Voucher Configuration',
    'voucher.invSettings': 'Inventory Settings',
    'voucher.displaySettings': 'Voucher Display Settings',
    'voucher.printPreviewMock': 'Print Preview (Mock)',
    'voucher.printPreviewDesc': 'Visual representation of current layout settings',
    'voucher.maintainInv': 'Maintain Inventory',
    'voucher.maintainGodowns': 'Maintain Godowns',
    'voucher.maintainBatches': 'Maintain Batches',
    'voucher.trackExpiry': 'Track Expiry Dates',
    'voucher.barcodeScanning': 'Barcode Scanning',
    'voucher.showFreeQty': 'Show Free Quantity',
    'voucher.showDiscPercent': 'Show Discount %',
    'voucher.showTaxPercent': 'Show Tax %',
    'voucher.enableMultiCurrency': 'Enable Multi-Currency',
    'voucher.enableTaxCalc': 'Enable Tax Calculation',
    'voucher.selectParticulars': 'Select Particulars...',
    'voucher.selectItem': 'Select Item...',
    'voucher.selectGodown': 'Select Godown...',
    'voucher.selectAccount': 'Select Account...',
    'voucher.selectParty': 'Select Party...',
    'common.nameOfItem': 'Name of Item',
    'common.drCr': 'Dr/Cr',
    'common.barcodeScan': 'Barcode Scan',
    'common.bankDetails': 'Bank Transaction Details',
    'common.transactionType': 'Transaction Type',
    'common.instNo': 'Inst. No.',
    'common.instDate': 'Inst. Date',
    'common.bankName': 'Bank Name',
    'common.narration': 'Narration',
    'common.subTotal': 'Sub Total',
    'common.taxAmount': 'Tax Amount',
    'common.discount': 'Discount',
    'common.totalAmount': 'Total Amount',
    'common.saveVoucher': 'Save Voucher',
    'common.print': 'Print',
    'common.downloadPdf': 'Download PDF',
    'common.clear': 'Clear',
    'common.share': 'Share',
    'features.subtitle': 'Explore the comprehensive suite of tools designed to help your business operate more efficiently and grow faster.',
    'features.feature1Title': 'Financial Management',
    'features.feature1Desc': 'Complete control over your finances with real-time reporting, automated bookkeeping, and advanced analytics.',
    'features.feature1Detail1': 'Automated Balance Sheets',
    'features.feature1Detail2': 'Profit & Loss Statements',
    'features.feature1Detail3': 'Real-time Cash Flow Tracking',
    'features.feature1Detail4': 'Multi-currency Support',
    'features.feature2Title': 'Inventory & Warehouse',
    'features.feature2Desc': 'Manage your stock levels across multiple locations, optimize reordering, and track every item in your supply chain.',
    'features.feature2Detail1': 'Multi-godown Management',
    'features.feature2Detail2': 'Batch & Expiry Tracking',
    'features.feature2Detail3': 'Automated Stock Alerts',
    'features.feature2Detail4': 'Barcode Integration',
    'features.feature3Title': 'Production & Manufacturing',
    'features.feature3Desc': 'Streamline your manufacturing process from order to delivery with integrated production planning and machine management.',
    'features.feature3Detail1': 'Order Management',
    'features.feature3Detail2': 'Machine Efficiency Tracking',
    'features.feature3Detail3': 'Production Reports',
    'features.feature3Detail4': 'Resource Allocation',
    'features.feature4Title': 'Payroll & HR',
    'features.feature4Desc': 'Manage your most valuable asset—your people. Handle payroll, attendance, and employee records in one place.',
    'features.feature4Detail1': 'Automated Salary Sheets',
    'features.feature4Detail2': 'Employee Master Records',
    'features.feature4Detail3': 'Attendance Tracking',
    'features.feature4Detail4': 'Performance Analytics',
    'features.moreTitle': 'And Much More',
    'features.moreSubtitle': 'Every detail considered for your business success.',
    'features.extra1Title': 'Security',
    'features.extra1Desc': 'Enterprise-grade security with end-to-end encryption.',
    'features.extra2Title': 'Speed',
    'features.extra2Desc': 'Lightning-fast performance for seamless operations.',
    'features.extra3Title': 'Reports',
    'features.extra3Desc': 'Comprehensive reporting and data visualization tools.',
    'features.extra4Title': 'Cloud',
    'features.extra4Desc': 'Access your data from anywhere, on any device.',
    'features.extra5Title': 'Real-time',
    'features.extra5Desc': 'Live updates and instant synchronization across all modules.',
    'features.extra6Title': 'Growth',
    'features.extra6Desc': 'Scalable infrastructure that grows with your business.',
    'features.extra7Title': 'Documents',
    'features.extra7Desc': 'Integrated document management and digital filing.',
    'features.extra8Title': 'Users',
    'features.extra8Desc': 'Role-based access control and team management.',

    // About Page
    'about.missionTitle': 'Our Mission',
    'about.missionDesc': 'We are dedicated to empowering businesses of all sizes with the tools they need to thrive in a digital-first world. Our goal is to simplify complex operations and provide clarity through intelligent data.',
    'about.bannerTitle': 'Built for Business',
    'about.bannerSubtitle': 'Founded in 2010, serving over 500+ companies worldwide.',
    'about.leadershipTitle': 'Our Leadership',
    'about.value1Title': 'Innovation',
    'about.value1Desc': 'Constantly pushing boundaries to provide cutting-edge solutions.',
    'about.value2Title': 'Customer First',
    'about.value2Desc': 'Your success is our priority. We grow when you grow.',
    'about.value3Title': 'Global Reach',
    'about.value3Desc': 'Serving businesses across 50+ countries with localized support.',
    'about.value4Title': 'Excellence',
    'about.value4Desc': 'Committed to the highest standards of quality and performance.',

    // Contact Page
    'contact.title': 'Get in Touch',
    'contact.subtitle': "Have questions? We're here to help. Send us a message and our team will get back to you within 24 hours.",
    'contact.emailLabel': 'Email Us',
    'contact.phoneLabel': 'Call Us',
    'contact.phone2': 'Mon-Fri, 9am-6pm EST',
    'contact.addressLabel': 'Visit Our Office',
    'contact.fullName': 'Full Name',
    'contact.fullNamePlaceholder': 'John Doe',
    'contact.emailAddress': 'Email Address',
    'contact.emailPlaceholder': 'john@example.com',
    'contact.subject': 'Subject',
    'contact.subjectPlaceholder': 'How can we help?',
    'contact.message': 'Message',
    'contact.messagePlaceholder': 'Tell us more about your needs...',
    'contact.sendMessage': 'Send Message',
    'contact.successTitle': 'Message Sent!',
    'contact.successMessage': 'Thank you for your message! We will get back to you soon.',
    'about.roleCEO': 'CEO & Founder',
    'about.roleCTO': 'CTO',
    'about.roleProduct': 'Head of Product',
    'nav.cashFlow': 'Cash Flow',
    'nav.fundsFlow': 'Funds Flow',
    'nav.groupVoucher': 'Group Voucher',
    'nav.contraRegister': 'Contra Register',
    'nav.paymentRegister': 'Payment Register',
    'nav.receiptRegister': 'Receipt Register',
    'nav.salesRegister': 'Sales Register',
    'nav.purchaseRegister': 'Purchase Register',
    'nav.journalRegister': 'Journal Register',
    'nav.statistics': 'Statistics',
    'subscription.upgradeExperience': 'Upgrade Your Experience',
    'subscription.choosePerfectPlan': 'Choose the perfect plan for your growing business',
    'subscription.monthly': 'Monthly',
    'subscription.yearly': 'Yearly',
    'subscription.savePercentage': 'SAVE {percent}%',
    'subscription.mostPopular': 'Most Popular',
    'subscription.currentPlan': 'Current Plan',
    'subscription.lowerTier': 'Lower Tier',
    'subscription.selectPlan': 'Select Plan',
    'subscription.selected': 'Selected',
    'subscription.upgradeTo': 'Upgrade to {plan}',
    'subscription.upgradeRequestDesc': 'You are requesting an upgrade to the {plan} plan billed {cycle}.',
    'subscription.totalAmountDue': 'Total Amount Due',
    'subscription.submitRequest': 'Submit Request',
    'subscription.contactSupport': 'Contact Support',
    'subscription.viewDocumentation': 'View Documentation',
    'subscription.orderId': 'Order ID',
    'subscription.plan': 'Plan',
    'subscription.amount': 'Amount',
    'subscription.status': 'Status',
    'subscription.date': 'Date',
    'subscription.actions': 'Actions',
    'subscription.active': 'Active',
    'subscription.trial': 'Trial',
    'subscription.inactive': 'Inactive',
    'subscription.freePlan': 'Free Plan',
    'subscription.freePlanDesc': 'Basic access to essential ERP features.',
    'subscription.noExpiry': 'No Expiry',
    'subscription.extra': 'Extra',
    'subscription.cancelRequest': 'Cancel Request',
    'subscription.unlimited': 'UNLIMITED',
    'subscription.trialAlert': 'You are currently on a trial plan. Upgrade to remove limits and unlock more features.',
    'subscription.equivMo': 'Equivalent to {amount} ৳/mo',
    'subscription.whatsIncluded': "What's included:",
    'subscription.moreFeatures': '+ {count} more features',
    'subscription.termsNotice': 'By clicking "Submit Request", you agree to our terms of service. Our team will contact you for payment details to activate your new plan.',

    'invBooks.title': 'Inventory Books',
    'invBooks.subtitle': 'Dive deep into your stock records and movements',
    'invBooks.locationDesc': 'Location-wise stock summary with quantity and value',
    'invBooks.stockSummaryDesc': 'Overview of all stock items with current quantity and value',
    'invBooks.stockItemDesc': 'Monthly summary of transactions for a specific item',
    'invBooks.stockGroupDesc': 'Stock status grouped by categories',
    'invBooks.stockCategoryDesc': 'Analysis of stock by defined categories',
    'invBooks.stockTransferDesc': 'Record of internal stock transfers between godowns',
    'invBooks.physicalStockDesc': 'History of physical stock adjustments and audits',
    'stockItem.title': 'Stock Item Monthly Summary',
    'stockItem.subtitle': 'Month-wise inward and outward movements',
    'stockItem.filterPlaceholder': 'Filter items...',
    'stockItem.currentStock': 'Current Stock:',
    'stockItem.selectPrompt': 'Select an item to view monthly summary',
    'stockItem.month': 'Month',
    'stockItem.inward': 'Inward',
    'stockItem.outward': 'Outward',
    'stockItem.netQty': 'Net Qty',
    'stockItem.qty': 'Quantity',
    'stockItem.val': 'Value',
    'subscription.noOrders': 'No subscription orders found.',
    'subscription.loadingOrders': 'Loading orders...',
    'nav.location': 'Location',
    'location.title': 'Location Summary',
    'location.subtitle': 'Godown-wise stock valuation',
    'location.netQty': 'Net Quantity',
    'location.closingValue': 'Closing Value',
    'location.totalAcross': 'Total Value Across All Locations',
    'location.noLocations': 'No locations found with stock data',
    'location.grandTotal': 'Grand Total',
    'nav.stockGroupSummary': 'Stock Group Summary',
    'nav.stockCategorySummary': 'Stock Category Summary',
    'nav.stockTransferRegister': 'Stock Transfer Register',
    'nav.physicalStockRegister': 'Physical Stock Register',
    'nav.ageingAnalysis': 'Ageing Analysis',
    'nav.paySlip': 'Pay Slip',
    'nav.paySheet': 'Pay Sheet',
    'nav.attendanceSheet': 'Attendance Sheet',
    'nav.paymentAdvice': 'Payment Advice',
    'nav.payrollStatement': 'Payroll Statement',
    'nav.payrollRegister': 'Payroll Register',
    'nav.attendanceRegister': 'Attendance Register',
    'nav.employeeProfile': 'Employee Profile',
    'nav.employeeHeadCount': 'Employee Head Count',
    'nav.groupSummary': 'Group Summary',
    'nav.stockQuery': 'Stock Query',
    'nav.movementAnalysis': 'Movement Analysis',
    'nav.cashBankBooks': 'Cash/Bank Books',
    'nav.stockItem': 'Stock Item',
    'nav.statementOfAccount': 'Statement of Account',
    'nav.ledger': 'Ledger',
  },
  bn: {
    // Navbar
    'nav.home': 'হোম',
    'nav.features': 'বৈশিষ্ট্য',
    'nav.pricing': 'প্রাইসিং',
    'nav.about': 'আমাদের সম্পর্কে',
    'nav.contact': 'যোগাযোগ',
    'nav.signIn': 'লগইন',
    'nav.getStarted': 'শুরু করুন',
    'nav.dashboard': 'ড্যাশবোর্ড',
    'nav.logout': 'লগআউট সেশন',
    'nav.settings': 'সেটিংস',
    'nav.profile': 'প্রোফাইল',
    'nav.founderPanel': 'ফাউন্ডার প্যানেল',
    'nav.masters': 'মাস্টার্স',
    'nav.createLedger': 'লেজার তৈরি করুন',
    'nav.createItem': 'আইটেম তৈরি করুন',
    'nav.godowns': 'গোডাউন',
    'nav.employeeMaster': 'কর্মচারী মাস্টার',
    'nav.chartOfAccounts': 'চার্ট অফ অ্যাকাউন্টস',
    'nav.itemMaster': 'আইটেম মাস্টার',
    'nav.alter': 'অল্টার',
    'nav.transactions': 'লেনদেন',
    'nav.voucherEntry': 'ভাউচার এন্ট্রি',
    'nav.payroll': 'পেরোল',
    'nav.payrollManagement': 'পেরোল ম্যানেজমেন্ট',
    'nav.production': 'উৎপাদন',
    'nav.orderManagement': 'অর্ডার ম্যানেজমেন্ট',
    'nav.machineManagement': 'মেশিন ম্যানেজমেন্ট',
    'nav.productionReports': 'উৎপাদন রিপোর্ট',
    'nav.reports': 'রিপোর্ট',
    'daybook.title': 'ডে-বুক',
    'daybook.loading': 'লেনদেন লোড হচ্ছে...',
    'daybook.noTransactions': 'কোনো লেনদেন রেকর্ড করা হয়নি',
    'daybook.noTransactionsPeriod': 'এই সময়ের জন্য কোনো লেনদেন রেকর্ড করা হয়নি',
    'daybook.viewDaybook': 'ডে-বুক দেখুন',
    'daybook.detailed': 'বিস্তারিত',
    'daybook.condensed': 'সংক্ষিপ্ত',
    'daybook.showNarration': 'ন্যারেশন দেখান',
    'daybook.showInventory': 'ইনভেন্টরি বিবরণ দেখান',
    'daybook.showEnteredBy': 'কে এন্ট্রি করেছে দেখান',
    'daybook.sortingMethod': 'সর্টিং পদ্ধতি',
    'daybook.downloadExcel': 'এক্সেল ডাউনলোড করুন',
    'daybook.downloadPDF': 'পিডিএফ ডাউনলোড করুন',
    'daybook.configureReport': 'রিপোর্ট কনফিগার করুন',
    'nav.balanceSheet': 'ব্যালেন্স শিট',
    'nav.trialBalance': 'ট্রায়াল ব্যালেন্স',
    'nav.profitAndLoss': 'লাভ ও ক্ষতি',
    'nav.ratioAnalysis': 'অনুপাত বিশ্লেষণ',
    'nav.financialInsights': 'আর্থিক অন্তর্দৃষ্টি',
    'nav.stockSummary': 'স্টক সারাংশ',
    'nav.ledgerStatement': 'লেজার স্টেটমেন্ট',
    'nav.accountBooks': 'অ্যাকাউন্ট বুকস',
    'nav.inventoryBooks': 'ইনভেন্টরি বুকস',
    'nav.statementOfInventory': 'ইনভেন্টরি স্টেটমেন্ট',
    'nav.statementOfInventoryShort': 'ইনভেন্টরি বিবরণী',
    'nav.payrollReports': 'পেরোল রিপোর্ট',
    'nav.negativeLedger': 'নেগেটিভ লেজার',
    'nav.negativeStock': 'নেগেটিভ স্টক',
    'nav.salesPerformance': 'বিক্রয় কর্মক্ষমতা',
    'nav.companyInfo': 'কোম্পানির তথ্য',
    'nav.uiCustomization': 'UI কাস্টমাইজেশন',
    'nav.voucherSettings': 'ভাউচার সেটিংস',
    'nav.printSettings': 'প্রিন্ট সেটিংস',
    'nav.f11Features': 'F11 ফিচারসমূহ',
    'nav.security': 'নিরাপত্তা',
    'nav.notifications': 'নোটিফিকেশন',
    'nav.whatsappTemplates': 'হোয়াটসঅ্যাপ টেমপ্লেট',
    'nav.utilities': 'ইউটিলিটিস',
    'nav.companyManagement': 'কোম্পানি ম্যানেজমেন্ট',
    'nav.notesMemo': 'নোট / মেমো',
    'nav.userManagement': 'ব্যবহারকারী ম্যানেজমেন্ট',
    'nav.menu': 'মেনু',
    'nav.theme': 'থিম নির্বাচন করুন',
    'nav.daybook': 'ডে-বুক',
    'nav.subscription': 'সাবস্ক্রিপশন',
    'subscription.title': 'সাবস্ক্রিপশন ম্যানেজমেন্ট',
    'subscription.subtitle': 'আপনার প্ল্যান পরিচালনা করুন, বিলিং ইতিহাস দেখুন এবং আপনার ফিচারগুলো আপগ্রেড করুন।',
    'subscription.usageLimits': 'ব্যবহারের সীমা',
    'subscription.upgradePlan': 'প্ল্যান আপগ্রেড করুন',
    'subscription.currentSubscription': 'বর্তমান সাবস্ক্রিপশন',
    'subscription.planType': 'প্ল্যানের ধরণ',
    'subscription.expiryDate': 'মেয়াদ উত্তীর্ণের তারিখ',
    'subscription.price': 'মূল্য',
    'subscription.featuresIncluded': 'অন্তর্ভুক্ত ফিচারসমূহ:',
    'subscription.orderHistory': 'অর্ডারের ইতিহাস',
    'subscription.needHelp': 'সাহায্য প্রয়োজন?',
    'subscription.needHelpDesc': 'আপনার সাবস্ক্রিপশন নিয়ে কোনো সমস্যা থাকলে বা আপনার ব্যবসার জন্য কাস্টম প্ল্যানের প্রয়োজন হলে, দয়া করে আমাদের সাপোর্ট টিমের সাথে যোগাযোগ করুন।',
    'subscription.paymentMethods': 'পেমেন্ট পদ্ধতিসমূহ',
    'subscription.paymentMethodsDesc': 'বর্তমানে আমরা শুধুমাত্র ম্যানুয়াল ব্যাংক ট্রান্সফার এবং মোবাইল ব্যাংকিং (বিকাশ/নগদ) সমর্থন করি।',
    'common.vouchers': 'ভাউচার',
    'common.items': 'আইটেম',
    'common.ledgers': 'লেজার',
    'common.users': 'ব্যবহারকারী',
    'common.godowns': 'গোডাউন',
    'common.employees': 'কর্মচারী',

    // Home
    'home.heroTitle': 'বুদ্ধিমত্তার সাথে আপনার ব্যবসা পরিচালনা করুন',
    'home.heroSubtitle': 'আধুনিক এন্টারপ্রাইজের জন্য অল-ইন-ওয়ান ইআরপি সমাধান। অপারেশন সহজ করুন, রিয়েল-টাইম ইনসাইট পান এবং আত্মবিশ্বাসের সাথে আপনার ব্যবসা বৃদ্ধি করুন।',
    'home.startTrial': 'ফ্রি ট্রায়াল শুরু করুন',
    'home.viewFeatures': 'বৈশিষ্ট্য দেখুন',
    'home.statsClients': 'সক্রিয় ক্লায়েন্ট',
    'home.statsUptime': 'আপটাইম রেট',
    'home.statsSupport': 'বিশেষজ্ঞ সাপোর্ট',
    'home.statsExperience': 'বছরের অভিজ্ঞতা',
    'home.featuresTitle': 'আপনার যা কিছু প্রয়োজন',
    'home.featuresSubtitle': 'একটি একক প্ল্যাটফর্ম থেকে আপনার ব্যবসার প্রতিটি দিক পরিচালনা করতে সাহায্য করার জন্য শক্তিশালী টুলস।',
    'home.feature1Title': 'আর্থিক অন্তর্দৃষ্টি',
    'home.feature1Desc': 'আপনাকে ডেটা-চালিত সিদ্ধান্ত নিতে সাহায্য করার জন্য রিয়েল-টাইম রিপোর্টিং এবং বিশ্লেষণ।',
    'home.feature2Title': 'ইনভেন্টরি নিয়ন্ত্রণ',
    'home.feature2Desc': 'স্টক লেভেল ট্র্যাক করুন, গুদাম পরিচালনা করুন এবং আপনার সাপ্লাই চেইন অপ্টিমাইজ করুন।',
    'home.feature3Title': 'টিম সহযোগিতা',
    'home.feature3Desc': 'সহজেই কর্মচারী, বেতন এবং অনুমতি পরিচালনা করুন।',
    'home.feature4Title': 'এন্টারপ্রাইজ নিরাপত্তা',
    'home.feature4Desc': 'আপনার সংবেদনশীল ব্যবসায়িক ডেটা নিরাপদ রাখতে ব্যাংক-গ্রেড নিরাপত্তা।',
    'home.feature5Title': 'দ্রুত পারফরম্যান্স',
    'home.feature5Desc': 'আপনার ব্যবসা যাতে কখনও ধীর না হয় তা নিশ্চিত করতে গতির জন্য অপ্টিমাইজ করা হয়েছে।',
    'home.feature6Title': 'ক্লাউড অ্যাক্সেস',
    'home.feature6Desc': 'যেকোনো ডিভাইস থেকে বিশ্বের যেকোনো প্রান্ত থেকে আপনার ব্যবসায়িক ডেটা অ্যাক্সেস করুন।',
    'home.ctaTitle': 'আপনার ব্যবসা পরিবর্তন করতে প্রস্তুত?',
    'home.ctaSubtitle': 'শত শত সফল কোম্পানির সাথে যোগ দিন যারা ইতিমধ্যে তাদের ব্যবসার প্রবৃদ্ধির জন্য আমাদের ইআরপি সিস্টেম ব্যবহার করছে।',
    'home.getStarted': 'এখনই শুরু করুন',

    // Footer
    'footer.description': 'একটি ব্যাপক ইআরপি সমাধান যা আপনার ব্যবসার কার্যক্রমকে সহজতর করার জন্য ডিজাইন করা হয়েছে, ইনভেন্টরি ম্যানেজমেন্ট থেকে শুরু করে আর্থিক রিপোর্টিং পর্যন্ত।',
    'footer.product': 'পণ্য',
    'footer.legal': 'আইনি',
    'footer.privacy': 'গোপনীয়তা নীতি',
    'footer.terms': 'পরিষেবার শর্তাবলী',

    // Auth
    'auth.signInTitle': 'ইআরপি সিস্টেমে সাইন ইন করুন',
    'auth.signInSubtitle': 'আপনার অ্যাকাউন্টে প্রবেশ করতে নিচে আপনার বিবরণ দিন।',
    'auth.email': 'ইমেইল ঠিকানা',
    'auth.password': 'পাসওয়ার্ড',
    'auth.forgotPassword': 'পাসওয়ার্ড ভুলে গেছেন?',
    'auth.signInButton': 'সাইন ইন',
    'auth.noAccount': "অ্যাকাউন্ট নেই?",
    'auth.createAccount': 'একটি তৈরি করুন',
    'auth.registerTitle': 'আপনার অ্যাকাউন্ট তৈরি করুন',
    'auth.registerSubtitle': 'আজই আমাদের সাথে যোগ দিন এবং স্মার্টলি আপনার ব্যবসা পরিচালনা শুরু করুন।',
    'auth.fullName': 'পুরো নাম',
    'auth.confirmPassword': 'পাসওয়ার্ড নিশ্চিত করুন',
    'auth.registerButton': 'অ্যাকাউন্ট তৈরি করুন',
    'auth.haveAccount': 'ইতিমধ্যে অ্যাকাউন্ট আছে?',

    // Dashboard
    'dash.welcome': 'স্বাগতম',
    'dash.overview': 'ড্যাশবোর্ড ওভারভিউ',
    'dash.financialSummary': 'আর্থিক সারাংশ',
    'dash.kpi': 'মূল কর্মক্ষমতা সূচক',
    'dash.revenue': 'মোট আয়',
    'dash.profit': 'নিট মুনাফা',
    'dash.activeLedgers': 'সক্রিয় লেজার',
    'dash.stockValue': 'স্টক ভ্যালু',
    'dash.activeUsers': 'সক্রিয় ব্যবহারকারী',
    'dash.newOrders': 'নতুন অর্ডার',
    'dash.pendingTasks': 'পেন্ডিং কাজ',
    'dash.recentActivity': 'সাম্প্রতিক কার্যক্রম',
    'dash.recentTransactions': 'সাম্প্রতিক লেনদেন',
    'dash.viewAll': 'সব দেখুন',
    'dash.viewDaybook': 'ডেবুক দেখুন',
    'dash.quickActions': 'দ্রুত অ্যাকশন',
    'dash.voucher': 'ভাউচার',
    'dash.item': 'আইটেম',
    'dash.ledger': 'লেজার',
    'dash.godown': 'গোডাউন',
    'dash.users': 'ব্যবহারকারী',
    'dash.revenueTrajectory': 'রাজস্ব গতিপথ',
    'dash.expenseDistribution': 'ব্যয় বন্টন',
    'dash.netProfitMargin': 'নিট মুনাফার মার্জিন',
    'dash.cashFlowProjection': 'ক্যাশ ফ্লো প্রজেকশন',
    'dash.gateway': 'গেটওয়ে',
    'dash.gatewayOf': 'গেটওয়ে অফ',
    'dash.technicalOverview': 'প্রযুক্তিগত ওভারভিউ',
    'dash.financialYear': 'আর্থিক বছর',
    'dash.from': 'থেকে',
    'dash.to': 'পর্যন্ত',
    'dash.trialPeriod': 'ট্রায়াল পিরিয়ড',
    'dash.subscriptionActive': 'সাবস্ক্রিপশন সক্রিয়',
    'dash.subscriptionInactive': 'সাবস্ক্রিপশন নিষ্ক্রিয়',
    'dash.plan': 'প্ল্যান',
    'dash.daysRemaining': 'দিন বাকি',
    'dash.expiresOn': 'মেয়াদ শেষ হবে',
    'dash.notSet': 'সেট করা হয়নি',
    'dash.renewPlan': 'প্ল্যান নবায়ন করুন',
    'dash.monthlySalesTrend': 'মাসিক বিক্রয়ের প্রবণতা',
    'dash.performanceMetrics': 'কর্মক্ষমতা মেট্রিক্স',
    'dash.revenueTarget': 'রাজস্ব লক্ষ্য',
    'dash.profitMargin': 'মুনাফার মার্জিন',
    'dash.stockTurnover': 'স্টক টার্নওভার',
    'dash.collectionEfficiency': 'সংগ্রহের দক্ষতা',
    'dash.support': 'সাপোর্ট',
    'dash.documentation': 'ডকুমেন্টেশন',
    'dash.systemStatus': 'সিস্টেম স্ট্যাটাস',
    'dash.online': 'অনলাইন',
    'dash.noRecentTransactions': 'কোন সাম্প্রতিক লেনদেন নেই',

    // Item
    'item.title': 'আইটেম মাস্টার',
    'item.new': 'নতুন আইটেম',
    'item.edit': 'আইটেম সম্পাদনা',
    'item.name': 'আইটেমের নাম',
    'item.category': 'ক্যাটাগরি',
    'item.partNo': 'পার্ট নং',
    'item.description': 'বিবরণ',
    'item.descriptionPlaceholder': 'আইটেমের বিবরণ লিখুন...',
    'item.unit': 'ইউনিট',
    'item.openingQty': 'প্রারম্ভিক পরিমাণ',
    'item.openingRate': 'প্রারম্ভিক হার',
    'item.hasBatches': 'ব্যাচ মেইনটেইন করুন',
    'item.hasExpiry': 'মেয়াদ শেষ মেইনটেইন করুন',
    'item.barcode': 'বারকোড',
    'item.lowStockThreshold': 'লো স্টক থ্রেশহোল্ড',
    'item.taxPercent': 'ট্যাক্স %',
    'item.generalItems': 'সাধারণ আইটেম',
    'item.schemeQty': 'স্কিম পরিমাণ',
    'item.schemeFreeQty': 'স্কিম ফ্রি পরিমাণ',
    'item.generalDetails': 'সাধারণ বিবরণ',
    'item.namePlaceholder': 'যেমন: আইফোন ১৫ প্রো, সিমেন্ট ব্যাগ',
    'item.categoryPlaceholder': 'যেমন: ইলেকট্রনিক্স, নির্মাণ',
    'item.partNoPlaceholder': 'যেমন: SKU-১২৩',
    'item.unitPlaceholder': 'ইউনিট নির্বাচন করুন',
    'item.openingQtyPlaceholder': '০.০০',
    'item.openingRatePlaceholder': '০.০০',
    'item.barcodePlaceholder': 'বারকোড স্ক্যান করুন বা লিখুন',
    'item.taxPercentPlaceholder': '০',
    'item.addNewCategory': 'নতুন ক্যাটাগরি যোগ করুন',
    'item.stockSettings': 'স্টক ও ট্র্যাকিং সেটিংস',
    'item.maintainBatches': 'ব্যাচ মেইনটেইন করুন',
    'item.maintainExpiry': 'মেয়াদ শেষ মেইনটেইন করুন',
    'item.lowStockPlaceholder': '০',
    'item.deleteWarning': 'এই আইটেমটির সিস্টেমে বিদ্যমান লেনদেন রয়েছে। এটি মুছে ফেললে আপনার আর্থিক রিপোর্টে অসঙ্গতি দেখা দেবে।',
    'item.deleteConfirmText': 'আপনি কি নিশ্চিত যে আপনি "{name}" মুছে ফেলতে চান? এই আইটেমটি আপনার ইনভেন্টরি থেকে স্থায়ীভাবে সরিয়ে ফেলা হবে।',
    'item.recommendKeep': 'এই আইটেমটি রাখা অত্যন্ত সুপারিশ করা হয়।',
    'item.masterView': 'মাস্টার ভিউ',
    'item.priceList': 'প্রাইস লিস্ট',
    'item.recalculateStats': 'পরিসংখ্যান পুনরায় গণনা করুন',
    'item.createNewItem': 'নতুন আইটেম তৈরি করুন',
    'item.searchPlaceholder': 'নাম বা পার্ট নং দিয়ে অনুসন্ধান করুন...',
    'item.totalItems': 'মোট আইটেম',
    'item.loadingInventory': 'ইনভেন্টরি লোড হচ্ছে...',
    'item.noItemsFound': 'আপনার মানদণ্ডের সাথে মেলে এমন কোনো আইটেম পাওয়া যায়নি',
    'item.standardPrice': 'স্ট্যান্ডার্ড মূল্য',
    'item.wholesalePrice': 'পাইকারি মূল্য',
    'item.retailPrice': 'খুচরা মূল্য',
    'item.avgCost': 'গড় খরচ',
    'item.currentStock': 'বর্তমান স্টক',
    'production.productionControl': 'প্রোডাকশন কন্ট্রোল',
    'production.newOrder': 'নতুন অর্ডার',
    'production.idle': 'সিস্টেম অলস',
    'production.processingJob': 'প্রিন্ট জব প্রসেস হচ্ছে',
    'production.readyForAssignment': 'এসাইনমেন্টের জন্য প্রস্তুত',
    'production.searchPlaceholder': 'ক্লায়েন্ট / আইটেম / ডিজাইন অনুসন্ধান করুন...',
    'production.noMachinesConfigured': 'কোনো মেশিন কনফিগার করা নেই। সেটিংসে মেশিন যোগ করুন।',
    'production.statusUpdateSuccess': 'অর্ডারের অবস্থা {status} এ আপডেট করা হয়েছে',
    'production.statusUpdateError': 'অবস্থা আপডেট করতে ব্যর্থ হয়েছে',
    'production.status.Pending': 'পেন্ডিং',
    'production.status.Printing': 'প্রিন্টিং',
    'production.status.Completed': 'সম্পন্ন',
    'production.status.Delivered': 'ডেলিভার করা হয়েছে',
    'production.status.Cancelled': 'বাতিল',
    'stock.title': 'স্টক সামারি',
    'stock.loading': 'স্টক ডেটা লোড হচ্ছে...',
    'stock.noItems': 'অনুসন্ধানের সাথে মেলে এমন কোনো স্টক আইটেম নেই',
    'stock.allGodowns': 'সব গুদাম',
    'stock.lowStockOnly': 'শুধুমাত্র লো স্টক',
    'stock.valuationMethod': 'মূল্যায়ন পদ্ধতি',
    'stock.weightedAvg': 'ওয়েটেড এভারেজ',
    'stock.quickCreateItem': 'দ্রুত আইটেম তৈরি',
    'stock.searchPlaceholder': 'আইটেম বা ক্যাটাগরি অনুসন্ধান করুন...',
    'stock.recalculate': 'পুনরায় গণনা',
    'stock.lowStock': 'লো স্টক',
    'reports.financial': 'আর্থিক রিপোর্ট',
    'reports.cashBankBook': 'ক্যাশ/ব্যাংক বুক',
    'reports.groupSummary': 'গ্রুপ সারাংশ',
    'reports.itemMonthly': 'আইটেম মাসিক সারাংশ',
    'reports.movementAnalysis': 'মুভমেন্ট বিশ্লেষণ',
    'reports.stockQuery': 'স্টক কোয়েরি',
    'reports.balanceSheet': 'ব্যালেন্স শিট',
    'reports.profitAndLoss': 'লাভ ও লোকসান হিসাব',
    'reports.trialBalance': 'রেওয়ামিল',
    'reports.asOnDate': 'তারিখ অনুযায়ী',
    'reports.liabilities': 'দায়সমূহ',
    'reports.assets': 'সম্পদসমূহ',
    'reports.totalLiabilities': 'মোট দায়',
    'reports.totalAssets': 'মোট সম্পদ',
    'reports.closingStock': 'সমাপনী মজুদ',
    'reports.netProfit': 'নিট লাভ',
    'reports.netLoss': 'নিট লোকসান',
    'reports.grossProfit': 'মোট লাভ',
    'reports.grossLoss': 'মোট লোকসান',
    'reports.openingStock': 'প্রারম্ভিক মজুদ',
    'reports.purchases': 'ক্রয়',
    'reports.sales': 'বিক্রয়',
    'reports.directExpenses': 'প্রত্যক্ষ খরচ',
    'reports.directIncomes': 'প্রত্যক্ষ আয়',
    'reports.indirectExpenses': 'পরোক্ষ খরচ',
    'reports.indirectIncomes': 'পরোক্ষ আয়',
    'reports.differenceInOpening': 'প্রারম্ভিক ব্যালেন্সের পার্থক্য',
    'reports.debit': 'ডেবিট',
    'reports.credit': 'ক্রেডিট',
    'reports.openingBalance': 'প্রারম্ভিক ব্যালেন্স',
    'reports.closingBalance': 'সমাপনী ব্যালেন্স',
    'reports.tradingAccount': 'ট্রেডিং অ্যাকাউন্ট',
    'reports.incomeStatement': 'আয় বিবরণী',
    'accounts.chartOfAccounts': 'চার্ট অফ অ্যাকাউন্টস',
    'accounts.hierarchy': 'লেজার এবং গ্রুপের অনুক্রম',
    'accounts.noLedgersInGroup': 'এই গ্রুপে কোনো লেজার নেই',
    'accounts.loadingHierarchy': 'অনুক্রম লোড হচ্ছে...',
    'ledger.statement': 'লেজার স্টেটমেন্ট',
    'ledger.selectToView': 'স্টেটমেন্ট দেখতে একটি লেজার নির্বাচন করুন',
    'ledger.loadingEntries': 'এন্ট্রি লোড হচ্ছে...',
    'ledger.noTransactions': 'এই সময়ের জন্য কোনো লেনদেন পাওয়া যায়নি',
    'ledger.vchType': 'ভাউচার টাইপ',
    'ledger.vchNo': 'ভাউচার নং',
    'ledger.openingBalance': 'প্রারম্ভিক ব্যালেন্স',
    'ledger.closingBalance': 'সমাপনী ব্যালেন্স',
    'ledger.runningBalance': 'রানিং ব্যালেন্স',
    'ledger.particulars': 'বিবরণ',
    'ledger.searchLedgers': 'লেজার অনুসন্ধান করুন...',
    'godown.title': 'গুদাম / লোকেশন মাস্টার',
    'godown.add': 'গুদাম যোগ করুন',
    'godown.edit': 'গুদাম সম্পাদনা করুন',
    'godown.name': 'গুদামের নাম',
    'godown.location': 'অবস্থান / ঠিকানা',
    'godown.contactPerson': 'যোগাযোগকারী ব্যক্তি',
    'godown.phoneNumber': 'ফোন নম্বর',
    'godown.description': 'বিবরণ',
    'godown.deleteConfirm': 'আপনি কি নিশ্চিত যে আপনি এই গুদামটি মুছে ফেলতে চান?',
    'godown.saveSuccess': 'গুদাম সফলভাবে সংরক্ষিত হয়েছে',
    'godown.updateSuccess': 'গুদাম সফলভাবে আপডেট করা হয়েছে',
    'godown.deleteSuccess': 'গুদাম সফলভাবে মুছে ফেলা হয়েছে',
    'godown.noGodowns': 'কোনো গুদাম পাওয়া যায়নি। শুরু করতে একটি তৈরি করুন।',
    'auth.register': 'নিবন্ধন করুন',
    'auth.backToLogin': 'লগইনে ফিরে যান',
    'auth.sendResetLink': 'রিসেট লিঙ্ক পাঠান',
    'auth.sending': 'পাঠানো হচ্ছে...',
    'company.subtitle': 'আপনার ব্যবসায়িক প্রতিষ্ঠানগুলো পরিচালনা করুন এবং তাদের মধ্যে পরিবর্তন করুন।',
    'company.logo': 'লোগো ইউআরএল',
    'company.switch': 'পরিবর্তন করুন',
    'company.current': 'বর্তমান',
    'company.createSuccess': 'নতুন কোম্পানি তৈরি এবং সফলভাবে পরিবর্তন করা হয়েছে!',
    'company.switchSuccess': 'সফলভাবে কোম্পানি পরিবর্তন করা হয়েছে!',
    'company.updateSuccess': 'কোম্পানি সফলভাবে আপডেট করা হয়েছে!',
    'company.deleteSuccess': 'কোম্পানি সফলভাবে মুছে ফেলা হয়েছে!',
    'company.noCompanies': 'কোনো কোম্পানি পাওয়া যায়নি।',
    'employee.title': 'কর্মচারী মাস্টার',
    'employee.subtitle': 'আপনার জনবল এবং কর্মচারীদের বিবরণ পরিচালনা করুন।',
    'employee.add': 'কর্মচারী যোগ করুন',
    'employee.edit': 'কর্মচারী সম্পাদনা করুন',
    'employee.name': 'কর্মচারীর নাম',
    'employee.designation': 'পদবী',
    'employee.department': 'বিভাগ',
    'employee.bloodGroup': 'রক্তের গ্রুপ',
    'employee.presentAddress': 'বর্তমান ঠিকানা',
    'employee.permanentAddress': 'স্থায়ী ঠিকানা',
    'employee.nidNumber': 'এনআইডি নম্বর',
    'employee.drivingLicense': 'ড্রাইভিং লাইসেন্স',
    'employee.passportNo': 'পাসপোর্ট নম্বর',
    'employee.bankName': 'ব্যাংকের নাম',
    'employee.bankBranch': 'ব্যাংকের শাখা',
    'employee.bankAccount': 'অ্যাকাউন্ট নম্বর',
    'employee.bankRouting': 'রাউটিং নম্বর',
    'employee.emergencyContact': 'জরুরী যোগাযোগ',
    'employee.emergencyRelation': 'সম্পর্ক',
    'employee.emergencyPhone': 'জরুরী ফোন',
    'employee.joiningDate': 'যোগদানের তারিখ',
    'employee.salary': 'বেতন',
    'employee.status': 'অবস্থা',
    'employee.active': 'সক্রিয়',
    'employee.inactive': 'নিষ্ক্রিয়',
    'employee.createSuccess': 'কর্মচারী সফলভাবে সংরক্ষণ করা হয়েছে',
    'employee.updateSuccess': 'কর্মচারী সফলভাবে আপডেট করা হয়েছে',
    'employee.deleteSuccess': 'কর্মচারী সফলভাবে মুছে ফেলা হয়েছে',
    'employee.deleteConfirm': 'আপনি কি নিশ্চিত যে আপনি এই কর্মচারীটি মুছে ফেলতে চান?',
    'employee.noEmployees': 'কোনো কর্মচারী পাওয়া যায়নি।',
    'employee.identification': 'পরিচয়পত্র',
    'employee.addressDetails': 'ঠিকানার বিবরণ',
    'employee.bankDetails': 'ব্যাংক অ্যাকাউন্টের বিবরণ',
    'employee.selectGroup': 'গ্রুপ নির্বাচন করুন',
    'employee.saveData': 'কর্মচারীর তথ্য সংরক্ষণ করুন',
    'employee.contactName': 'যোগাযোগের নাম',
    'employee.branchName': 'শাখার নাম',

    // Ledger
    'ledger.title': 'লেজার মাস্টার',
    'ledger.new': 'নতুন লেজার',
    'ledger.edit': 'লেজার সম্পাদনা',
    'ledger.name': 'লেজারের নাম',
    'ledger.alias': 'অ্যালিয়াস',
    'ledger.group': 'গ্রুপের অধীনে',
    'ledger.mailingDetails': 'মেইলিং বিবরণ',
    'ledger.address': 'ঠিকানা',
    'ledger.division': 'বিভাগ',
    'ledger.country': 'দেশ',
    'ledger.postalCode': 'পোস্টাল কোড',
    'ledger.mobile': 'মোবাইল নং',
    'ledger.email': 'ইমেইল',
    'ledger.website': 'ওয়েবসাইট',
    'ledger.contactDetails': 'যোগাযোগের বিবরণ',
    'ledger.bankDetails': 'ব্যাংক বিবরণ',
    'ledger.bankingDetails': 'ব্যাংকিং বিবরণ',
    'ledger.billWise': 'বিল-ভিত্তিক মেইনটেইন করুন',
    'ledger.vatNo': 'ভ্যাট নং',
    'ledger.generalDetails': 'সাধারণ বিবরণ',
    'ledger.namePlaceholder': 'যেমন: কোম্পানির নাম',
    'ledger.aliasPlaceholder': 'বিকল্প নাম',
    'ledger.under': 'গ্রুপের অধীনে',
    'ledger.billByBill': 'বিল-বাই-বিল ব্যালেন্স মেইনটেইন করুন',
    'ledger.costCenters': 'কস্ট সেন্টার প্রযোজ্য',
    'ledger.interestCalculation': 'সুদ গণনা সক্রিয় করুন',
    'ledger.provideContactDetails': 'যোগাযোগের বিবরণ দিন',
    'ledger.contactPerson': 'যোগাযোগকারীর নাম',
    'ledger.phone': 'ফোন নং',
    'ledger.provideBankDetails': 'ব্যাংক বিবরণ দিন',
    'ledger.transactionType': 'লেনদেনের ধরণ',
    'ledger.cheque': 'চেক',
    'ledger.eFundTransfer': 'ই-ফান্ড ট্রান্সফার',
    'ledger.other': 'অন্যান্য',
    'ledger.accountNo': 'অ্যাকাউন্ট নং',
    'ledger.bankCode': 'ব্যাংক কোড (IFSC/Swift)',
    'ledger.bankName': 'ব্যাংকের নাম',
    'ledger.recommendKeep': 'এই লেজারটি রাখা অত্যন্ত সুপারিশ করা হয়।',
    'ledger.deleteWarning': 'এই লেজারটির সিস্টেমে বিদ্যমান লেনদেন রয়েছে। এটি মুছে ফেললে আপনার আর্থিক রিপোর্টে অসঙ্গতি দেখা দেবে।',
    'ledger.deleteConfirmText': 'আপনি কি নিশ্চিত যে আপনি "{name}" মুছে ফেলতে চান? এই লেজারটি আপনার চার্ট অফ অ্যাকাউন্টস থেকে স্থায়ীভাবে সরিয়ে ফেলা হবে।',
    'ledger.creditLimit': 'ক্রেডিট লিমিট',

    // Settings
    'settings.title': 'সেটিংস',
    'settings.systemSettings': 'সিস্টেম সেটিংস',
    'settings.configureEnvironment': 'আপনার ইআরপি এনভায়রনমেন্ট কনফিগার করুন',
    'settings.profile': 'প্রোফাইল সেটিংস',
    'settings.language': 'ভাষা',
    'settings.selectLanguage': 'ভাষা নির্বাচন করুন',
    'settings.notifications': 'নোটিফিকেশন',
    'settings.security': 'নিরাপত্তা',
    'settings.save': 'পরিবর্তন সংরক্ষণ করুন',
    'settings.companyInfo': 'কোম্পানির তথ্য',
    'settings.companyName': 'কোম্পানির নাম',
    'settings.companyLogo': 'কোম্পানির লোগো',
    'settings.removeLogo': 'লোগো সরান',
    'settings.companySlogan': 'কোম্পানির স্লোগান',
    'settings.companyAddress': 'কোম্পানির ঠিকানা',
    'settings.financialYearStart': 'আর্থিক বছরের শুরু',
    'settings.reportSettings': 'রিপোর্ট সেটিংস',
    'settings.reportLayoutStyle': 'রিপোর্ট লেআউট স্টাইল',
    'settings.uiCustomization': 'ইউআই কাস্টমাইজেশন',
    'settings.menuBarStyle': 'মেনু বার স্টাইল',
    'settings.classicSidebar': 'ক্লাসিক সাইডবার (ডিফল্ট)',
    'settings.ribbonStyle': 'মাইক্রোসফট অফিস রিবন',
    'settings.macosStyle': 'macOS টপ মেনু বার',
    'settings.windows11Style': 'উইন্ডোজ ১১ টাস্কবার স্টাইল',
    'settings.menuBarStyleDesc': 'আপনার পছন্দের নেভিগেশন লেআউট চয়ন করুন।',
    'subscription.active': 'সক্রিয়',
    'subscription.trial': 'ট্রায়াল',
    'subscription.inactive': 'নিষ্ক্রিয়',
    'subscription.freePlan': 'ফ্রি প্ল্যান',
    'subscription.freePlanDesc': 'প্রয়োজনীয় ইআরপি বৈশিষ্ট্যগুলোতে মৌলিক অ্যাক্সেস।',
    'subscription.noExpiry': 'কোনো মেয়াদ শেষ নেই',
    'subscription.extra': 'অতিরিক্ত',
    'subscription.cancelRequest': 'অনুরোধ বাতিল করুন',
    'subscription.unlimited': 'অসীমিত',
    'subscription.trialAlert': 'আপনি বর্তমানে একটি ট্রায়াল প্ল্যানে আছেন। সীমা অপসারণ এবং আরও বৈশিষ্ট্য আনলক করতে আপগ্রেড করুন।',
    'subscription.equivMo': 'Equivalent to {amount} ৳/mo',
    'subscription.whatsIncluded': 'যা যা অন্তর্ভুক্ত আছে:',
    'subscription.moreFeatures': '+ {count} আরও বৈশিষ্ট্য',
    'subscription.termsNotice': '"অনুরোধ জমা দিন" ক্লিক করে, আপনি আমাদের পরিষেবার শর্তাবলীতে সম্মত হন। আপনার নতুন প্ল্যান সক্রিয় করার জন্য পেমেন্ট বিশদ জানতে আমাদের দল আপনার সাথে যোগাযোগ করবে।',

    'invBooks.title': 'ইনভেন্টরি বুকস',
    'invBooks.subtitle': 'আপনার স্টক রেকর্ড এবং মুভমেন্টের বিস্তারিত দেখুন',
    'invBooks.locationDesc': 'পরিমাণ এবং মূল্য সহ লোকেশন-ভিত্তিক স্টক সারাংশ',
    'invBooks.stockSummaryDesc': 'বর্তমান পরিমাণ এবং মূল্য সহ সমস্ত স্টক আইটেমের ওভারভিউ',
    'invBooks.stockItemDesc': 'একটি নির্দিষ্ট আইটেমের লেনদেনের মাসিক সারাংশ',
    'invBooks.stockGroupDesc': 'স্টক গ্রুপ অনুযায়ী সংক্ষিপ্ত বিবরণ',
    'invBooks.stockCategoryDesc': 'নির্ধারিত ক্যাটাগরি অনুযায়ী স্টক বিশ্লেষণ',
    'invBooks.stockTransferDesc': 'গোডাউনগুলোর মধ্যে অভ্যন্তরীণ স্টক স্থানান্তরের রেকর্ড',
    'invBooks.physicalStockDesc': 'শারীরিক স্টক সমন্বয় এবং অডিটের ইতিহাস',
    'stockItem.title': 'স্টক আইটেম মাসিক সারাংশ',
    'stockItem.subtitle': 'মাস-ভিত্তিক ইনওয়ার্ড এবং আউটওয়ার্ড মুভমেন্ট',
    'stockItem.filterPlaceholder': 'আইটেম ফিল্টার করুন...',
    'stockItem.currentStock': 'বর্তমান স্টক:',
    'stockItem.selectPrompt': 'মাসিক সারাংশ দেখতে একটি আইটেম নির্বাচন করুন',
    'stockItem.month': 'মাস',
    'stockItem.inward': 'ইনওয়ার্ড',
    'stockItem.outward': 'আউটওয়ার্ড',
    'stockItem.netQty': 'নেট পরিমাণ',
    'stockItem.qty': 'পরিমাণ',
    'stockItem.val': 'মূল্য',
    'settings.showDiscPercentDesc': 'ডিসকাউন্ট শতাংশ কলাম সক্রিয়/নিষ্ক্রিয় করুন।',
    'settings.showTaxPercent': 'ট্যাক্স % দেখান',
    'settings.showTaxPercentDesc': 'ট্যাক্স শতাংশ কলাম সক্রিয়/নিষ্ক্রিয় করুন।',
    'settings.theme': 'থিম নির্বাচন করুন',
    'settings.sidebarExpanded': 'ডিফল্টভাবে সাইডবার প্রসারিত',
    'settings.glassBackground': 'গ্লাস ব্যাকগ্রাউন্ড ইফেক্ট',
    'settings.notificationAnimation': 'নোটিফিকেশন অ্যানিমেশন',

    // Common
    'common.loading': 'লোড হচ্ছে...',
    'common.from': 'হতে',
    'common.to': 'পর্যন্ত',
    'common.f12Configure': 'F12: কনফিগার',
    'common.excel': 'এক্সেল',
    'common.pdf': 'পিডিএফ',
    'common.vchType': 'ভাউচারের ধরণ',
    'common.vchNo': 'ভাউচার নং',
    'common.total': 'মোট',
    'common.select': 'নির্বাচন করুন',
    'common.debit': 'ডেবিট',
    'common.credit': 'ক্রেডিট',
    'common.clearVoucher': 'ভাউচার পরিষ্কার করুন',
    'common.csv': 'সিএসভি',
    'common.recalculate': 'পুনরায় গণনা করুন',
    'common.totalValue': 'মোট মূল্য',
    'common.avgRate': 'গড় হার',
    'common.value': 'মূল্য',
    'common.grandTotal': 'সর্বমোট',
    'common.f1Help': 'F1: সাহায্য',
    'common.group': 'গ্রুপ',
    'common.searchPlaceholder': 'অনুসন্ধান করুন...',
    'common.noData': 'কোন তথ্য নেই',
    'common.error': 'একটি ত্রুটি ঘটেছে',
    'common.success': 'সফল হয়েছে',
    'common.cancel': 'বাতিল',
    'common.delete': 'মুছে ফেলুন',
    'common.edit': 'সম্পাদনা',
    'common.save': 'সংরক্ষণ',
    'common.refresh': 'রিফ্রেশ',
    'common.search': 'অনুসন্ধান',
    'common.filter': 'ফিল্টার',
    'common.actions': 'অ্যাকশন',
    'common.phone': 'ফোন নম্বর',
    'common.date': 'তারিখ',
    'common.amount': 'পরিমাণ',
    'common.status': 'অবস্থা',
    'common.type': 'ধরণ',
    'common.particulars': 'বিবরণ',
    'common.voucherNo': 'ভাউচার নং',
    'common.creation': 'তৈরি',
    'common.alteration': 'পরিবর্তন',
    'alter.groups': 'গ্রুপ',
    'alter.ledgers': 'লেজার',
    'alter.stockItems': 'স্টক আইটেম',
    'alter.voucherTypes': 'ভাউচার টাইপ',
    'alter.stockCategories': 'স্টক ক্যাটাগরি',
    'alter.units': 'ইউনিট',
    'alter.locations': 'গোডাউন',
    'alter.employeeGroups': 'পদবী',
    'alter.employees': 'কর্মচারী',
    'alter.creditLimit': 'ক্রেডিট লিমিট',
    'common.update': 'আপডেট',
    'common.create': 'তৈরি করুন',
    'common.confirmDeletion': 'মুছে ফেলার নিশ্চিতকরণ',
    'common.cannotUndone': 'এই কাজটি আর ফিরিয়ে আনা যাবে না',
    'common.warning': 'সতর্কতা',
    'common.confirmDelete': 'মুছা নিশ্চিত করুন',
    'common.voucherType': 'ভাউচারের ধরণ',
    'common.partyName': 'পার্টির নাম',
    'common.quick': 'দ্রুত',
    'common.itemName': 'আইটেমের নাম',
    'common.account': 'অ্যাকাউন্ট',
    'common.englishFont': 'ইংরেজি ফন্ট',
    'common.banglaFont': 'বাংলা ফন্ট',
    'common.selectFont': 'ফন্ট নির্বাচন করুন',
    'common.referenceNo': 'রেফারেন্স নং',
    'common.currency': 'মুদ্রা',
    'common.exchangeRate': 'বিনিময় হার',
    'common.exchangeRateDesc': 'বিনিময় হার: লেনদেনের মুদ্রাকে মূল মুদ্রায় রূপান্তর করার গুণক।',
    'common.currentBalance': 'বর্তমান ব্যালেন্স',
    'common.salesLedger': 'বিক্রয় লেজার',
    'common.purchaseLedger': 'ক্রয় লেজার',
    'common.salesperson': 'বিক্রয়কর্মী',
    'common.providedBy': 'প্রদানকারী',
    'common.receivedBy': 'গ্রহণকারী',
    'common.godown': 'গুদাম',
    'common.batch': 'ব্যাচ',
    'common.expiry': 'মেয়াদ উত্তীর্ণ',
    'common.quantity': 'পরিমাণ',
    'common.free': 'ফ্রি',
    'common.rate': 'দর',
    'common.per': 'প্রতি',
    'common.discPercent': 'ছাড় %',
    'common.taxPercent': 'ট্যাক্স %',
    'common.addItem': 'আইটেম যোগ করুন',
    'common.deleteItem': 'আইটেম মুছুন',
    'common.disc': 'ডিসকাউন্ট',
    'common.taka': 'টাকা',
    'common.percent': 'শতাংশ',
    'common.tax': 'ট্যাক্স',
    'common.whatsapp': 'হোয়াটসঅ্যাপ',
    'common.email': 'ইমেইল',
    'common.close': 'বন্ধ করুন',
    'common.clearVoucherConfirm': 'আপনি কি নিশ্চিত যে আপনি সমস্ত ভাউচার ডেটা মুছে ফেলতে চান? এই কাজটি পূর্বাবস্থায় ফেরানো যাবে না।',
    'common.back': 'ফিরে যান',
    'common.next': 'পরবর্তী',
    'common.basicInfo': 'প্রাথমিক তথ্য',
    'common.upload': 'আপলোড',
    'common.of': 'এর',
    'common.step': 'ধাপ',
    'common.staff': 'স্টাফ',
    'common.user': 'ব্যবহারকারী',
    'common.switchCompany': 'কোম্পানি পরিবর্তন করুন',
    'common.goTo': 'যাও',
    'common.profileNotFound': 'প্রোফাইল পাওয়া যায়নি',
    'common.profileNotFoundDesc': 'আপনার অ্যাকাউন্ট বিদ্যমান, কিন্তু আমরা আপনার ইআরপি প্রোফাইল খুঁজে পাইনি। এটি হতে পারে যদি আপনার অ্যাকাউন্ট ম্যানুয়ালি তৈরি করা হয়ে থাকে বা রেজিস্ট্রেশনের সময় কোনো ত্রুটি ঘটে থাকে।',
    'common.signOutTryAgain': 'সাইন আউট করুন এবং আবার চেষ্টা করুন',
    'common.loggedInAs': 'লগ ইন করা আছে:',
    'common.erpSystem': 'ইআরপি সিস্টেম',
    'common.logout': 'লগ আউট',
    'common.selectTheme': 'থিম নির্বাচন করুন',
    'common.allApps': 'সব অ্যাপ',
    'common.pinnedApps': 'পিন করা অ্যাপ',
    'common.searchResults': 'অনুসন্ধান ফলাফল',
    'common.noResultsFound': 'কোন ফলাফল পাওয়া যায়নি',
    'common.searchAppsPlaceholder': 'অ্যাপ, সেটিংস এবং ডকুমেন্ট অনুসন্ধান করুন',
    'common.placeholderWarning': 'আপনি বর্তমানে একটি প্লেসহোল্ডার কোম্পানিতে আছেন। আপনার তথ্য অন্য কোম্পানিতে থাকতে পারে।',
    'common.reportsGroupNotFound': 'রিপোর্ট গ্রুপ পাওয়া যায়নি',
    'common.configureReportsGroup': 'দয়া করে ফাউন্ডার প্যানেলে রিপোর্ট গ্রুপ কনফিগার করুন।',
    'nav.accounting': 'অ্যাকাউন্টিং',
    'nav.inventory': 'ইনভেন্টরি',
    'nav.exceptionReports': 'এক্সেপশন রিপোর্ট',
    'voucher.config': 'ভাউচার কনফিগারেশন',
    'voucher.invSettings': 'ইনভেন্টরি সেটিংস',
    'voucher.displaySettings': 'ভাউচার ডিসপ্লে সেটিংস',
    'voucher.printPreviewMock': 'প্রিন্ট প্রিভিউ (মক)',
    'voucher.printPreviewDesc': 'বর্তমান লেআউট সেটিংসের ভিজ্যুয়াল উপস্থাপনা',
    'voucher.maintainInv': 'ইনভেন্টরি মেইনটেইন করুন',
    'voucher.maintainGodowns': 'গোডাউন মেইনটেইন করুন',
    'voucher.maintainBatches': 'ব্যাচ মেইনটেইন করুন',
    'voucher.trackExpiry': 'মেয়াদ শেষ হওয়ার তারিখ ট্র্যাক করুন',
    'voucher.barcodeScanning': 'বারকোড স্ক্যানিং',
    'voucher.showFreeQty': 'ফ্রি পরিমাণ দেখান',
    'voucher.showDiscPercent': 'ডিসকাউন্ট % দেখান',
    'voucher.showTaxPercent': 'ট্যাক্স % দেখান',
    'voucher.enableMultiCurrency': 'মাল্টি-কারেন্সি সক্ষম করুন',
    'voucher.enableTaxCalc': 'ট্যাক্স গণনা সক্ষম করুন',
    'voucher.selectParticulars': 'বিবরণ নির্বাচন করুন...',
    'voucher.selectItem': 'আইটেম নির্বাচন করুন...',
    'voucher.selectGodown': 'গোডাউন নির্বাচন করুন...',
    'voucher.selectAccount': 'অ্যাকাউন্ট নির্বাচন করুন...',
    'voucher.selectParty': 'পার্টি নির্বাচন করুন...',
    'common.nameOfItem': 'আইটেমের নাম',
    'common.drCr': 'ডেবিট/ক্রেডিট',
    'common.barcodeScan': 'বারকোড স্ক্যান',
    'common.bankDetails': 'ব্যাংক লেনদেনের বিবরণ',
    'common.transactionType': 'লেনদেনের ধরণ',
    'common.instNo': 'ইন্সট্রুমেন্ট নং',
    'common.instDate': 'ইন্সট্রুমেন্ট তারিখ',
    'common.bankName': 'ব্যাংকের নাম',
    'common.narration': 'বিবরণ',
    'common.subTotal': 'উপ-মোট',
    'common.taxAmount': 'ট্যাক্স পরিমাণ',
    'common.discount': 'ছাড়',
    'common.totalAmount': 'মোট পরিমাণ',
    'common.saveVoucher': 'ভাউচার সংরক্ষণ করুন',
    'common.print': 'প্রিন্ট',
    'common.downloadPdf': 'পিডিএফ ডাউনলোড',
    'common.clear': 'পরিষ্কার করুন',
    'features.subtitle': 'আপনার ব্যবসাকে আরও দক্ষতার সাথে পরিচালনা করতে এবং দ্রুত বৃদ্ধি করতে সাহায্য করার জন্য ডিজাইন করা সরঞ্জামগুলির ব্যাপক সেটটি অন্বেষণ করুন।',
    'features.feature1Title': 'আর্থিক ব্যবস্থাপনা',
    'features.feature1Desc': 'রিয়েল-টাইম রিপোর্টিং, স্বয়ংক্রিয় বুককিপিং এবং উন্নত বিশ্লেষণের মাধ্যমে আপনার অর্থের ওপর পূর্ণ নিয়ন্ত্রণ।',
    'features.feature1Detail1': 'স্বয়ংক্রিয় ব্যালেন্স শিট',
    'features.feature1Detail2': 'লাভ ও ক্ষতির বিবরণ',
    'features.feature1Detail3': 'রিয়েল-টাইম ক্যাশ ফ্লো ট্র্যাকিং',
    'features.feature1Detail4': 'মাল্টি-কারেন্সি সাপোর্ট',
    'features.feature2Title': 'ইনভেন্টরি ও গুদাম',
    'features.feature2Desc': 'একাধিক অবস্থানে আপনার স্টক লেভেল পরিচালনা করুন, রিঅর্ডারিং অপ্টিমাইজ করুন এবং আপনার সাপ্লাই চেইনের প্রতিটি আইটেম ট্র্যাক করুন।',
    'features.feature2Detail1': 'মাল্টি-গোডাউন ম্যানেজমেন্ট',
    'features.feature2Detail2': 'ব্যাচ ও মেয়াদ ট্র্যাকিং',
    'features.feature2Detail3': 'স্বয়ংক্রিয় স্টক অ্যালার্ট',
    'features.feature2Detail4': 'বারকোড ইন্টিগ্রেশন',
    'features.feature3Title': 'উৎপাদন ও ম্যানুফ্যাকচারিং',
    'features.feature3Desc': 'অর্ডার থেকে ডেলিভারি পর্যন্ত আপনার ম্যানুফ্যাকচারিং প্রক্রিয়াকে সমন্বিত উৎপাদন পরিকল্পনা এবং মেশিন ম্যানেজমেন্টের মাধ্যমে সহজতর করুন।',
    'features.feature3Detail1': 'অর্ডার ম্যানেজমেন্ট',
    'features.feature3Detail2': 'মেশিন দক্ষতা ট্র্যাকিং',
    'features.feature3Detail3': 'উৎপাদন রিপোর্ট',
    'features.feature3Detail4': 'রিসোর্স অ্যালোকেশন',
    'features.feature4Title': 'পেরোল ও এইচআর',
    'features.feature4Desc': 'আপনার সবচেয়ে মূল্যবান সম্পদ—আপনার কর্মীদের পরিচালনা করুন। বেতন, উপস্থিতি এবং কর্মচারীদের রেকর্ড এক জায়গায় হ্যান্ডেল করুন।',
    'features.feature4Detail1': 'স্বয়ংক্রিয় স্যালারি শিট',
    'features.feature4Detail2': 'কর্মচারী মাস্টার রেকর্ড',
    'features.feature4Detail3': 'উপস্থিতি ট্র্যাকিং',
    'features.feature4Detail4': 'পারফরম্যান্স অ্যানালিটিক্স',
    'features.moreTitle': 'এবং আরও অনেক কিছু',
    'features.moreSubtitle': 'আপনার ব্যবসার সাফল্যের জন্য প্রতিটি বিবরণ বিবেচনা করা হয়েছে।',
    'features.extra1Title': 'নিরাপত্তা',
    'features.extra1Desc': 'এন্ড-টু-এন্ড এনক্রিপশন সহ এন্টারপ্রাইজ-গ্রেড নিরাপত্তা।',
    'features.extra2Title': 'গতি',
    'features.extra2Desc': 'নির্বিঘ্ন ক্রিয়াকলাপের জন্য বিদ্যুৎ-গতি সম্পন্ন কর্মক্ষমতা।',
    'features.extra3Title': 'রিপোর্ট',
    'features.extra3Desc': 'ব্যাপক রিপোর্টিং এবং ডেটা ভিজ্যুয়ালাইজেশন সরঞ্জাম।',
    'features.extra4Title': 'ক্লাউড',
    'features.extra4Desc': 'যেকোনো ডিভাইস থেকে যেকোনো জায়গা থেকে আপনার ডেটা অ্যাক্সেস করুন।',
    'features.extra5Title': 'রিয়েল-টাইম',
    'features.extra5Desc': 'সমস্ত মডিউল জুড়ে লাইভ আপডেট এবং তাৎক্ষণিক সিঙ্ক্রোনাইজেশন।',
    'features.extra6Title': 'বৃদ্ধি',
    'features.extra6Desc': 'স্কেলেবল অবকাঠামো যা আপনার ব্যবসার সাথে বৃদ্ধি পায়।',
    'features.extra7Title': 'নথিপত্র',
    'features.extra7Desc': 'ইন্টিগ্রেটেড ডকুমেন্ট ম্যানেজমেন্ট এবং ডিজিটাল ফাইলিং।',
    'features.extra8Title': 'ব্যবহারকারী',
    'features.extra8Desc': 'ভূমিকা-ভিত্তিক অ্যাক্সেস কন্ট্রোল এবং টিম ম্যানেজমেন্ট।',

    // About Page
    'about.missionTitle': 'আমাদের লক্ষ্য',
    'about.missionDesc': 'আমরা ডিজিটাল-প্রথম বিশ্বে উন্নতির জন্য প্রয়োজনীয় সরঞ্জামগুলির মাধ্যমে সব ধরণের ব্যবসাকে ক্ষমতায়ন করতে নিবেদিত। আমাদের লক্ষ্য হলো জটিল ক্রিয়াকলাপগুলিকে সহজ করা এবং বুদ্ধিমান ডেটার মাধ্যমে স্বচ্ছতা প্রদান করা।',
    'about.bannerTitle': 'ব্যবসার জন্য নির্মিত',
    'about.bannerSubtitle': '২০১০ সালে প্রতিষ্ঠিত, বিশ্বজুড়ে ৫০০+ এরও বেশি কোম্পানিকে সেবা দিচ্ছে।',
    'about.leadershipTitle': 'আমাদের নেতৃত্ব',
    'about.value1Title': 'উদ্ভাবন',
    'about.value1Desc': 'অত্যাধুনিক সমাধান প্রদানের জন্য ক্রমাগত সীমানা অতিক্রম করা।',
    'about.value2Title': 'গ্রাহক প্রথম',
    'about.value2Desc': 'আপনার সাফল্য আমাদের অগ্রাধিকার। আপনি যখন বাড়বেন তখন আমরাও বাড়ব।',
    'about.value3Title': 'বিশ্বব্যাপী নাগাল',
    'about.value3Desc': 'স্থানীয় সহায়তার মাধ্যমে ৫০+ দেশে ব্যবসাকে সেবা দিচ্ছে।',
    'about.value4Title': 'উৎকর্ষ',
    'about.value4Desc': 'গুণমান এবং কর্মক্ষমতার সর্বোচ্চ মান বজায় রাখতে প্রতিশ্রুতিবদ্ধ।',

    // Contact Page
    'contact.title': 'যোগাযোগ করুন',
    'contact.subtitle': 'প্রশ্ন আছে? আমরা সাহায্য করতে এখানে আছি। আমাদের একটি বার্তা পাঠান এবং আমাদের টিম ২৪ ঘন্টার মধ্যে আপনার সাথে যোগাযোগ করবে।',
    'contact.emailLabel': 'আমাদের ইমেইল করুন',
    'contact.phoneLabel': 'আমাদের কল করুন',
    'contact.phone2': 'সোম-শুক্র, সকাল ৯টা - সন্ধ্যা ৬টা EST',
    'contact.addressLabel': 'আমাদের অফিস ভিজিট করুন',
    'contact.fullName': 'পুরো নাম',
    'contact.fullNamePlaceholder': 'জন ডো',
    'contact.emailAddress': 'ইমেইল ঠিকানা',
    'contact.emailPlaceholder': 'john@example.com',
    'contact.subject': 'বিষয়',
    'contact.subjectPlaceholder': 'আমরা কীভাবে সাহায্য করতে পারি?',
    'contact.message': 'বার্তা',
    'contact.messagePlaceholder': 'আপনার প্রয়োজন সম্পর্কে আমাদের আরও বলুন...',
    'contact.sendMessage': 'বার্তা পাঠান',
    'contact.successTitle': 'বার্তা পাঠানো হয়েছে!',
    'contact.successMessage': 'আপনার বার্তার জন্য ধন্যবাদ! আমরা শীঘ্রই আপনার সাথে যোগাযোগ করব।',
    'about.roleCEO': 'সিইও এবং প্রতিষ্ঠাতা',
    'about.roleCTO': 'সিটিও',
    'about.roleProduct': 'পণ্য প্রধান',
    'nav.cashFlow': 'ক্যাশ ফ্লো',
    'nav.fundsFlow': 'ফান্ডস ফ্লো',
    'nav.groupVoucher': 'গ্রুপ ভাউচার',
    'nav.contraRegister': 'কন্ট্রা রেজিস্টার',
    'nav.paymentRegister': 'পেমেন্ট রেজিস্টার',
    'nav.receiptRegister': 'রিসিট রেজিস্টার',
    'nav.salesRegister': 'সেলস রেজিস্টার',
    'nav.purchaseRegister': 'পারচেজ রেজিস্টার',
    'nav.journalRegister': 'জার্নাল রেজিস্টার',
    'nav.statistics': 'পরিসংখ্যান',
    'subscription.upgradeExperience': 'আপনার অভিজ্ঞতা আপগ্রেড করুন',
    'subscription.choosePerfectPlan': 'আপনার বর্ধনশীল ব্যবসার জন্য উপযুক্ত প্ল্যান বেছে নিন',
    'subscription.totalAmountDue': 'মোট প্রদেয় পরিমাণ',
    'subscription.submitRequest': 'অনুরোধ জমা দিন',
    'subscription.mostPopular': 'সবচেয়ে জনপ্রিয়',
    'subscription.lowerTier': 'নিম্নতর টিয়ার',
    'subscription.selected': 'নির্বাচিত',
    'subscription.selectPlan': 'প্ল্যান নির্বাচন করুন',
    'subscription.savePercentage': 'সংরক্ষণ করুন {percent}%',
    'subscription.contactSupport': 'সাপোর্ট যোগাযোগ করুন',
    'subscription.viewDocumentation': 'ডকুমেন্টেশন দেখুন',
    'subscription.orderId': 'অর্ডার আইডি',
    'subscription.plan': 'প্ল্যান',
    'subscription.amount': 'পরিমাণ',
    'subscription.status': 'অবস্থা',
    'subscription.date': 'তারিখ',
    'subscription.actions': 'অ্যাকশন',

    'subscription.noOrders': 'কোনো সাবস্ক্রিপশন অর্ডার পাওয়া যায়নি।',
    'subscription.loadingOrders': 'অর্ডার লোড হচ্ছে...',
    'nav.location': 'লোকেশন',
    'location.title': 'লোকেশন সারাংশ',
    'location.subtitle': 'গোডাউন অনুযায়ী স্টক মূল্যায়ন',
    'location.netQty': 'নেট পরিমাণ',
    'location.closingValue': 'ক্লোজিং ভ্যালু',
    'location.totalAcross': 'সব লোকেশন জুড়ে মোট মূল্য',
    'location.noLocations': 'স্টক ডেটা সহ কোনো লোকেশন পাওয়া যায়নি',
    'location.grandTotal': 'সর্বমোট',
    'nav.stockGroupSummary': 'স্টক গ্রুপ সারাংশ',
    'nav.stockCategorySummary': 'স্টক ক্যাটাগরি সারাংশ',
    'nav.stockTransferRegister': 'স্টক ট্রান্সফার রেজিস্টার',
    'nav.physicalStockRegister': 'ফিজিক্যাল স্টক রেজিস্টার',
    'nav.ageingAnalysis': 'এজিং অ্যানালাইসিস',
    'nav.paySlip': 'পে স্লিপ',
    'nav.paySheet': 'পে শিট',
    'nav.attendanceSheet': 'অ্যাটেনডেন্স শিট',
    'nav.paymentAdvice': 'পেমেন্ট অ্যাডভাইস',
    'nav.payrollStatement': 'পেরোল স্টেটমেন্ট',
    'nav.payrollRegister': 'পেরোল রেজিস্টার',
    'nav.attendanceRegister': 'অ্যাটেনডেন্স রেজিস্টার',
    'nav.employeeProfile': 'কর্মচারী প্রোফাইল',
    'nav.employeeHeadCount': 'কর্মচারী সংখ্যা',
    'nav.groupSummary': 'গ্রুপ সারাংশ',
    'nav.stockQuery': 'স্টক কোয়েরি',
    'nav.movementAnalysis': 'মুভমেন্ট অ্যানালাইসিস',
    'nav.cashBankBooks': 'ক্যাশ/ব্যাংক বুকস',
    'nav.stockItem': 'স্টক আইটেম',
    'nav.statementOfAccount': 'স্টেটমেন্ট অফ অ্যাকাউন্ট',
    'nav.ledger': 'লেজার',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('app_language');
    return (saved as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app_language', lang);
  };

  const t = (key: string, variables?: Record<string, string | number>): string => {
    let translation = translations[language][key];
    
    // Fallback to English if missing in target language
    if (translation === undefined && language !== 'en') {
      translation = translations['en'][key];
    }

    if (translation === undefined) {
      // Intelligent fallback: Convert key to readable title (e.g., 'item.currentStock' -> 'Current Stock')
      const parts = key.split('.');
      const lastPart = parts[parts.length - 1];
      translation = lastPart
        .replace(/([A-Z])/g, ' $1') // Add space before capital letters
        .replace(/[_-]/g, ' ')      // Replace underscores/hyphens with spaces
        .trim()
        .replace(/^\w/, (c) => c.toUpperCase()) // Capitalize first letter
        .split(' ')
        .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
        .join(' ');
    }

    if (variables) {
      Object.entries(variables).forEach(([k, v]) => {
        translation = translation.replace(`{${k}}`, String(v));
      });
    }
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
