import { 
  Package, 
  Users, 
  Printer, 
  BarChart3, 
  Bell, 
  StickyNote, 
  Search, 
  Settings, 
  FileText, 
  MessageSquare, 
  ClipboardList, 
  MapPin, 
  ListTree, 
  BookOpen, 
  PieChart, 
  Activity, 
  Cpu, 
  Shield, 
  Building2, 
  Scale, 
  TrendingUp, 
  CreditCard 
} from 'lucide-react';

export const AVAILABLE_FEATURES = [
  { id: 'inv', label: 'Inventory Management', icon: Package },
  { id: 'payroll', label: 'Payroll & Employees', icon: Users },
  { id: 'production', label: 'Production & Orders', icon: Printer },
  { id: 'insights', label: 'Financial Insights', icon: BarChart3 },
  { id: 'notifications', label: 'System Notifications', icon: Bell },
  { id: 'notes', label: 'Sticky Notes', icon: StickyNote },
  { id: 'search', label: 'Global Search', icon: Search },
  { id: 'ui_custom', label: 'UI Customization', icon: Settings },
  { id: 'report_layout', label: 'Report Layout Style', icon: FileText },
  { id: 'popup_notif', label: 'Popup Notifications', icon: Bell },
  { id: 'whatsapp_temp', label: 'WhatsApp Templates', icon: MessageSquare },
  { id: 'voucher_entry', label: 'Voucher Entry', icon: ClipboardList },
  { id: 'godowns', label: 'Godown Management', icon: MapPin },
  { id: 'employee_master', label: 'Employee Master', icon: Users },
  { id: 'chart_accounts', label: 'Chart of Accounts', icon: ListTree },
  { id: 'item_master', label: 'Item Master', icon: Package },
  { id: 'daybook', label: 'Daybook Reports', icon: BookOpen },
  { id: 'financial_reports', label: 'Financial Reports (BS/PL/TB)', icon: BarChart3 },
  { id: 'ratio_analysis', label: 'Ratio Analysis', icon: PieChart },
  { id: 'sales_perf', label: 'Sales Performance', icon: Activity },
  { id: 'voucher_settings', label: 'Voucher Settings', icon: Settings },
  { id: 'print_settings', label: 'Print Settings', icon: Printer },
  { id: 'f11_features', label: 'F11 Features', icon: Cpu },
  { id: 'security', label: 'Security Settings', icon: Shield },
  { id: 'utilities', label: 'System Utilities', icon: Settings },
  { id: 'company_mgmt', label: 'Company Management', icon: Building2 },
  { id: 'user_mgmt', label: 'User Management', icon: Users },
  { id: 'ledger_statement', label: 'Ledger Statement', icon: ClipboardList },
  { id: 'stock_summary', label: 'Stock Summary', icon: Package },
  { id: 'trial_balance', label: 'Trial Balance', icon: ClipboardList },
  { id: 'balance_sheet', label: 'Balance Sheet', icon: Scale },
  { id: 'profit_loss', label: 'Profit & Loss', icon: TrendingUp },
  { id: 'order_mgmt', label: 'Order Management', icon: Printer },
  { id: 'machine_mgmt', label: 'Machine Management', icon: Cpu },
  { id: 'production_reports', label: 'Production Reports', icon: BarChart3 },
  { id: 'subscription', label: 'Subscription Management', icon: CreditCard }
];
